/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dataCustomer;

import DB_koneksi.DB;
import Sopir.formSopirv2;
import alert.alert_hapus;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import functions.pop_upClear;
import functions.pop_upDataGagal;
import functions.pop_upDataberhasil;
import functions.pop_upRequired;
import functions.pop_upTanyaClear;
import functions.pop_upnoData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sakab
 */
public class formCustomerv2 extends javax.swing.JFrame {

    String id;
    Custv2 customer;

    /**
     * Creates new form formCustomer
     */
    public formCustomerv2(String kd_customer, Custv2 customer) {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        jScrollPane1.setBorder(null);
        id = kd_customer;
        this.customer = customer;
        if (kd_customer != null) {
            getData(kd_customer);
            kodeCust.setText(kd_customer);

        }
        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveMobil = new javax.swing.JButton();
        jButton_hapus = new javax.swing.JButton();
        kodeCust = new javax.swing.JTextField();
        no_ktp = new javax.swing.JTextField();
        namaLengkap = new javax.swing.JTextField();
        no_telp = new javax.swing.JTextField();
        jLabel_save = new javax.swing.JLabel();
        jLabel_clear = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamat1 = new javax.swing.JTextArea();

        saveMobil.setBackground(new java.awt.Color(255, 0, 51));
        saveMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saveMobil.setForeground(new java.awt.Color(255, 255, 255));
        saveMobil.setText("Save");
        saveMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMobilActionPerformed(evt);
            }
        });

        jButton_hapus.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kodeCust.setBackground(new java.awt.Color(238, 218, 222));
        kodeCust.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        kodeCust.setEnabled(false);
        getContentPane().add(kodeCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 350, 40));

        no_ktp.setBackground(new java.awt.Color(238, 218, 222));
        no_ktp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        no_ktp.setBorder(null);
        getContentPane().add(no_ktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 330, 30));

        namaLengkap.setBackground(new java.awt.Color(238, 218, 222));
        namaLengkap.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        namaLengkap.setBorder(null);
        getContentPane().add(namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 320, 30));

        no_telp.setBackground(new java.awt.Color(238, 218, 222));
        no_telp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        no_telp.setBorder(null);
        no_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_telpActionPerformed(evt);
            }
        });
        getContentPane().add(no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 320, 40));

        jLabel_save.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel_save.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_save.setText("Simpan");
        jLabel_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_saveMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 110, 50));

        jLabel_clear.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel_clear.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_clear.setText("Reset");
        jLabel_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_clearMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 110, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        alamat.setBackground(new java.awt.Color(238, 218, 222));
        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        alamat.setRows(5);
        alamat.setBorder(null);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 510, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modal_cust.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -1, 1040, 670));

        alamat1.setBackground(new java.awt.Color(238, 218, 222));
        alamat1.setColumns(20);
        alamat1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        alamat1.setRows(5);
        alamat1.setBorder(null);
        jScrollPane3.setViewportView(alamat1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 530, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getData(String kd_customer) {
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM customer  where kd_customer ='" + kd_customer + "'");

            while (res.next()) {

                namaLengkap.setText(res.getString("nama_lengkap"));
                no_ktp.setText(res.getString("no_ktp"));
                no_telp.setText(res.getString("no_telp"));
                alamat.setText(res.getString("alamat"));
//                     res.getString("gambar"),
//                    status.setText(res.getString("nopol"));
            }
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }
    private void saveMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMobilActionPerformed

    }//GEN-LAST:event_saveMobilActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton_hapusActionPerformed

    private void no_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_telpActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
    public void clear() {
        namaLengkap.setText(null);
        no_ktp.setText(null);
        alamat.setText(null);
        no_telp.setText(null);
    }
    private void jLabel_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clearMouseClicked
        // TODO add your handling code here:

        try {
            //pop_upTanyaClear tanya = new pop_upTanyaClear();
//          tanya.setVisible(true);
//            if (JOptionPane.showConfirmDialog(null, "Yakin ingin mengkosongkan seluruh data ?", "Pesan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
//                namaLengkap.setText(null);
//                no_ktp.setText(null);
//                alamat.setText(null);
//                no_telp.setText(null);
            pop_upTanyaClear clear = new pop_upTanyaClear(this);
            clear.setVisible(true);
//            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jLabel_clearMouseClicked

    private void jLabel_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saveMouseClicked
        // TODO add your handling code here:
        String nama = namaLengkap.getText();
        String noktp = no_ktp.getText();
        String noTlp = no_telp.getText();
        String Alamat = alamat.getText();
        String num = kodeCust.getText();

        if (nama.isEmpty() || noktp.isEmpty() || noTlp.isEmpty() || Alamat.isEmpty()) {
            pop_upRequired required = new pop_upRequired();
            required.setVisible(true);
            return;
        }
        //        String gambar = gambarMobil.getText();
        //        String status = statusMobil.getText();

        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql;
            if (id != null) {
                sql = "UPDATE customer SET nama_lengkap = '" + namaLengkap.getText() + "', no_ktp = '" + no_ktp.getText() + "',alamat = '" + alamat.getText() + "',no_telp = '" + no_telp.getText() + "' WHERE kd_customer = '" + kodeCust.getText() + "'";
                pop_upDataberhasil dataubah = new pop_upDataberhasil();
                dataubah.setVisible(true);
                PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Perubahan data Customer";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                }
            } else {
                ResultSet res = statement.executeQuery("SELECT genCustomerID() AS cusID");
                String kdCus = "";
                if (res.next()) {
                    kdCus = res.getString("cusID");
                }
                sql = "insert into customer VALUES('" + kdCus + "','" + nama + "', '" + noktp + "','" + Alamat + "', '" + noTlp + "');";

                PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Penambahan data Customer";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                }
            }
            statement.executeUpdate(sql);
            pop_upDataberhasil dataubah = new pop_upDataberhasil();
            dataubah.setVisible(true);
            customer.datatable();
            statement.close();

            this.dispose();

        } catch (Exception e) {
            System.out.println(e);
            pop_upDataGagal datagagal = new pop_upDataGagal();
            datagagal.setVisible(true);
        }
    }//GEN-LAST:event_jLabel_saveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formCustomerv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formCustomerv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formCustomerv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formCustomerv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formCustomerv2(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextArea alamat1;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_clear;
    private javax.swing.JLabel jLabel_save;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kodeCust;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JTextField no_ktp;
    private javax.swing.JTextField no_telp;
    private javax.swing.JButton saveMobil;
    // End of variables declaration//GEN-END:variables
}
