/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pengembalian;
import java.sql.*;
import java.util.Date;
import DB_koneksi.DB;
import Pembatalan.pembatalan;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.text.SimpleDateFormat;
/**
 *
 * @author sakab
 */
public class Detail_kembali extends javax.swing.JPanel {
    public String id;
    /**
     * Creates new form Detail_kembali
     */
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");

    public Detail_kembali(String id_pengembalian) {
        initComponents();
        this.id = id_pengembalian;
        setupTable();
        getData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kd_tranksaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nama_admin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama_penyewa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        no_ktp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_pengembalian = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_total = new javax.swing.JLabel();
        j_kembali = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        cetak = new javax.swing.JButton();
        cetak1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(177, 16, 7));
        jLabel8.setText("Detail Pengembalian");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Kd Transaksi");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 71, -1, -1));
        add(kd_tranksaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 72, 147, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Nama Admin");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 100, -1, -1));
        add(nama_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 101, 147, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Nama Penyewa");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 129, -1, -1));
        add(nama_penyewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 130, 146, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("No.KTP");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 129, -1, -1));
        add(no_ktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 130, 133, -1));

        jTable_pengembalian.setBackground(new java.awt.Color(238, 218, 222));
        jTable_pengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_pengembalian.setPreferredSize(new java.awt.Dimension(600, 80));
        jTable_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_pengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_pengembalian);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 930, 160));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Total");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Bayar");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Kembali");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel_total.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel_total.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_total.setText("70000");
        add(jLabel_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        j_kembali.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        j_kembali.setForeground(new java.awt.Color(177, 0, 7));
        j_kembali.setText("70000");
        add(j_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        bayar.setBackground(new java.awt.Color(204, 204, 204));
        bayar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bayar.setForeground(new java.awt.Color(204, 0, 0));
        add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 104, -1));

        cetak.setBackground(new java.awt.Color(255, 0, 51));
        cetak.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cetak.setForeground(new java.awt.Color(255, 255, 255));
        cetak.setText("Cetak");
        add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        cetak1.setBackground(new java.awt.Color(255, 0, 51));
        cetak1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cetak1.setForeground(new java.awt.Color(255, 255, 255));
        cetak1.setText("Pelanggaran");
        cetak1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cetak1MouseClicked(evt);
            }
        });
        add(cetak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cetak1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cetak1MouseClicked
        // TODO add your handling code here:
        Pelanggaran frm_langgar = new Pelanggaran(null);
        frm_langgar.setVisible(true);
    }//GEN-LAST:event_cetak1MouseClicked

    private void jTable_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_pengembalianMouseClicked
        int baris = jTable_pengembalian.rowAtPoint(evt.getPoint());
        String id_detail = jTable_pengembalian.getValueAt(baris, 0).toString();   
        String status = jTable_pengembalian.getValueAt(baris,11).toString();
        String id_supir = String.valueOf(jTable_pengembalian.getValueAt(baris, 3));
        String id_mobil = jTable_pengembalian.getValueAt(baris, 1).toString();

        try{
             Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT kd_mobil, kd_supir FROM detail_sewa where kd_detail_sewa='" + id_detail + "'");
            if (res.next()) { 
                String id_mobil1 = res.getString("kd_mobil");
                String id_supir1 = res.getString("kd_supir");
                  if (status.equals("diproses")) {
                // munculkan form pembatalan    
                      Pembatalan.pembatalan frm_batal = new Pembatalan.pembatalan(id_detail);
                      frm_batal.setVisible(true);
//              

                System.out.println("Proses");
            } else if (status.equals("perjalanan")) {
                int opsi = JOptionPane.showConfirmDialog(null, "Apakah Ada Kerusakan / Pelanggaran ?", "Peringatan", JOptionPane.YES_NO_OPTION);
                if (opsi == JOptionPane.YES_OPTION) {
//                Pelanggaran pgr = new Pelanggaran();
//                pgr.setVisible(true);
//                    String kdSewa = kd_transaksi.getText();
//                    Pelanggaran pgr = new Pelanggaran(kdSewa, id_mobil, nama_penyewa.getText());
//                    pgr.setVisible(true);
                } else {
                    String tglKembali = String.valueOf(new Date());
                    statement.executeUpdate("UPDATE detail_sewa SET tgl_kembali='" + tglKembali + "' , status='selesai' WHERE kd_detail_sewa='" + id_detail + "'");
                    statement.execute("UPDATE mobil SET status='tersedia' WHERE kd_mobil = '" + id_mobil1 + "'");
                    if (id_supir != null) {
                        statement.execute("UPDATE supir SET status='bersedia' WHERE kd_supir = '" + id_supir1 + "'");
                    }
                    JOptionPane.showMessageDialog(null, "Berhasil Update Data");
                }
            }
            }
        }catch(Exception x){
            JOptionPane.showMessageDialog(null, x);
        }
    }//GEN-LAST:event_jTable_pengembalianMouseClicked

    void setupTable(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Detail");
        tbl.addColumn("Kode Mobil");
        tbl.addColumn("Nama Mobil");
        tbl.addColumn("Kode Supir");
        tbl.addColumn("Nama Supir");
        tbl.addColumn("Harga Perhari");
        tbl.addColumn("Jml Hari");
        tbl.addColumn("Tgl Sewa");
        tbl.addColumn("Tgl Tenggat");
        tbl.addColumn("Tgl Kembali");
        tbl.addColumn("Subtotal");
        tbl.addColumn("Status");
        
        jTable_pengembalian.setModel(tbl);
        try{
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT detail_sewa.*, mobil.nama_mobil,mobil.nopol, supir.nama_supir FROM detail_sewa INNER JOIN mobil ON mobil.kd_mobil = detail_sewa.kd_mobil LEFT JOIN supir ON detail_sewa.kd_supir = supir.kd_supir WHERE kd_penyewaan = '"+ id +"';");
            System.out.println("SELECT detail_sewa.*, mobil.nama_mobil,mobil.nopol, supir.nama_supir FROM detail_sewa INNER JOIN mobil ON mobil.kd_mobil = detail_sewa.kd_mobil INNER JOIN supir ON detail_sewa.kd_supir = supir.kd_supir WHERE kd_penyewaan = '"+ id +"';");
            while(res.next()){
                String mobil = res.getString("nama_mobil") + " - " + res.getString("nopol");
                tbl.addRow(new Object[]{
                    res.getString("kd_detail_sewa"),  
                    res.getString("kd_mobil"),   
                    mobil,
                    res.getString("kd_supir"),
                    res.getString("nama_supir"),
                    res.getString("harga_perhari"),
                    res.getString("jml_hari"),
                    res.getString("tgl_sewa"),
                    res.getString("tgl_tenggat"),
                    res.getString("tgl_kembali"),
                    res.getString("subtotal"),
                    res.getString("status")
                });
                jTable_pengembalian.setModel(tbl);
            }
        }catch(Exception x){
            System.out.println(x);
            JOptionPane.showMessageDialog(null, x);
        }
    }
    
    
    void getData(){
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT penyewaan.*,user.nama_lengkap AS nm_admin,customer.nama_lengkap AS nm_cust,customer.no_ktp FROM penyewaan INNER JOIN customer on customer.kd_customer = penyewaan.kd_customer INNER JOIN user ON user.kd_user = penyewaan.kd_user where penyewaan.kd_penyewaan = '"+id+"'");
            
            while(res.next()){
                kd_tranksaksi.setText(res.getString("kd_penyewaan"));
                nama_admin.setText(res.getString("nm_admin"));
                nama_penyewa.setText(res.getString("nm_cust"));
                no_ktp.setText(res.getString("no_ktp"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton cetak;
    private javax.swing.JButton cetak1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_total;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_pengembalian;
    private javax.swing.JLabel j_kembali;
    private javax.swing.JTextField kd_tranksaksi;
    private javax.swing.JTextField nama_admin;
    private javax.swing.JTextField nama_penyewa;
    private javax.swing.JTextField no_ktp;
    // End of variables declaration//GEN-END:variables
}
