/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pengembalian;

import Pembatalan.*;
import Pembatalan.Form_Pembatalanv2;
import java.awt.*;
import java.awt.event.WindowEvent;
import DB_koneksi.DB;
import DB_koneksi.DB;
import Pembatalan.Form_Pembatalanv2;
import functions.pop_upDataberhasil;
import functions.pop_upKetRusak;
import functions.pop_upRequired;
import functions.pop_upnoData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sakab
 */
public class form_dendaPengembalian extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    String kode_detail_sewa, kd_pengembalian;
    Pengembalianv2 v;
    
    public form_dendaPengembalian(String kode_detail_sewa, String kd_pengembalian, Pengembalianv2 v) {
        initComponents();
        this.kode_detail_sewa = kode_detail_sewa;
        this.kd_pengembalian = kd_pengembalian;
        jScrollPane2.setBorder(null);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        setVisible(false);
        this.v = v;
        getData(kode_detail_sewa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kode_detail = new javax.swing.JTextField();
        harga_denda = new javax.swing.JTextField();
        btnSave = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama_mobil = new javax.swing.JTextField();
        tgl_sewa = new javax.swing.JTextField();
        tgl_tenggat = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        jumlah_hari = new javax.swing.JTextField();
        nama_supir = new javax.swing.JTextField();
        harga_perhari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        keterangan_kerusakan = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(1027, 659));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kode_detail.setBackground(new java.awt.Color(238, 218, 222));
        kode_detail.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        kode_detail.setEnabled(false);
        kode_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_detailActionPerformed(evt);
            }
        });
        getContentPane().add(kode_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 270, 40));

        harga_denda.setBackground(new java.awt.Color(238, 218, 222));
        harga_denda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        harga_denda.setBorder(null);
        getContentPane().add(harga_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 210, 30));

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 130, 50));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, -1));

        nama_mobil.setBackground(new java.awt.Color(238, 218, 222));
        nama_mobil.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nama_mobil.setEnabled(false);
        getContentPane().add(nama_mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 270, 40));

        tgl_sewa.setBackground(new java.awt.Color(238, 218, 222));
        tgl_sewa.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tgl_sewa.setEnabled(false);
        getContentPane().add(tgl_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 270, 40));

        tgl_tenggat.setBackground(new java.awt.Color(238, 218, 222));
        tgl_tenggat.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tgl_tenggat.setEnabled(false);
        getContentPane().add(tgl_tenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 270, 40));

        subtotal.setBackground(new java.awt.Color(238, 218, 222));
        subtotal.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        subtotal.setEnabled(false);
        getContentPane().add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 210, 40));

        jumlah_hari.setBackground(new java.awt.Color(238, 218, 222));
        jumlah_hari.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jumlah_hari.setEnabled(false);
        getContentPane().add(jumlah_hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 270, 40));

        nama_supir.setBackground(new java.awt.Color(238, 218, 222));
        nama_supir.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nama_supir.setEnabled(false);
        getContentPane().add(nama_supir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 270, 40));

        harga_perhari.setBackground(new java.awt.Color(238, 218, 222));
        harga_perhari.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        harga_perhari.setEnabled(false);
        getContentPane().add(harga_perhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 210, 40));

        keterangan_kerusakan.setBackground(new java.awt.Color(238, 218, 222));
        keterangan_kerusakan.setColumns(20);
        keterangan_kerusakan.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        keterangan_kerusakan.setForeground(new java.awt.Color(0, 0, 0));
        keterangan_kerusakan.setRows(5);
        keterangan_kerusakan.setBorder(null);
        jScrollPane2.setViewportView(keterangan_kerusakan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 260, 130));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/form denda pengembalian.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1027, 659));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
 void getData(String kd_detail_sewa) {
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM v_detailsewa  where kd_detail_sewa ='" + kd_detail_sewa + "'");

            while (res.next()) {
                kode_detail.setText(res.getString("kd_detail_sewa"));
                harga_perhari.setText(res.getString("harga_perhari"));
                nama_mobil.setText(res.getString("nama_mobil"));

tgl_sewa.setText(res.getString("tgl_sewa"));
                    tgl_tenggat.setText(res.getString("tgl_tenggat"));
                    jumlah_hari.setText(res.getString("jml_hari"));
                    subtotal.setText(res.getString("subtotal"));
  if (res.getString("nama_supir") != null && !res.getString("nama_supir").isEmpty()) {
                    nama_supir.setText(res.getString("nama_supir"));
                } else {
                    nama_supir.setText("Tidak Ada Sopir");
                }
                    
                   

//                     res.getString("gambar"),
//                    status.setText(res.getString("nopol"));
                }
            }catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
        }
    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked

        String denda_pembatalan = harga_denda.getText();
        String rusak = keterangan_kerusakan.getText();

        String kd_detail_sewa = this.kode_detail_sewa;
        String kd_pengembalian = this.kd_pengembalian;
        
        if (rusak.isEmpty()) {
            pop_upKetRusak required = new pop_upKetRusak();
            required.setVisible(true);
            return;
        }

        try {
//            System.out.println(kode_detail);
            Statement Statement = DB.getConnection().createStatement();
            String sql, sql1;
            LocalDate tgl_pengembalian = LocalDate.now();

            sql = "insert into pengembalian VALUES('" + kd_pengembalian + "','" + kd_detail_sewa + "'"
                    + ",'" + tgl_pengembalian + "' , '" + rusak + "','" + denda_pembatalan + "');";
            Statement.executeUpdate(sql);
            pop_upDataberhasil dataubah = new pop_upDataberhasil();
                dataubah.setVisible(true);
            sql1 = "update detail_sewa set status = 'selesai' where kd_detail_sewa = '" + kd_detail_sewa + "'";
            Statement.executeUpdate(sql1);
            pop_upDataberhasil dataudbah = new pop_upDataberhasil();
                dataudbah.setVisible(true);
            this.v.generateTablePengembalianMaster();
            this.dispose();
                      PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Pengembalian Transaksi Dengan denda";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                } 
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void kode_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_detailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_detailActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Denda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Denda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Denda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Denda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_dendaPengembalian(null, null, null).setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSave;
    private javax.swing.JTextField harga_denda;
    private javax.swing.JTextField harga_perhari;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah_hari;
    private javax.swing.JTextArea keterangan_kerusakan;
    private javax.swing.JTextField kode_detail;
    private javax.swing.JTextField nama_mobil;
    private javax.swing.JTextField nama_supir;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tgl_sewa;
    private javax.swing.JTextField tgl_tenggat;
    // End of variables declaration//GEN-END:variables

}
