/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pengembalian;

import Pembatalan.*;
import DB_koneksi.DB;

import Pengembalian.Detail_kembali;
import functions.pop_upDataberhasil;
import functions.pop_upTanyaPengembalian;
import functions.pop_upnoData;
import java.awt.Checkbox;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.ComboBoxEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import rental.Dashboardadmin;
import rental.login;

/**
 *
 * @author sakab
 */
public class Form_Pengembalianv2 extends javax.swing.JFrame {

    Dashboardadmin dashboard;
    String kode_detail_sewa = "";
    Pengembalianv2 v;

    public Form_Pengembalianv2(Pengembalianv2 v) {
        this.dashboard = dashboard;
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        getDetailSewa(jTextField_search.getText());
        this.setLocationRelativeTo(null);
        this.v = v;
    }

    public void getDetailSewa(String kd_penyewaan) {
        DefaultTableModel tbl = new DefaultTableModel();

        tbl.addColumn("kode Detail");
        tbl.addColumn("Nama Mobil");
        tbl.addColumn("Nama Sopir");
        tbl.addColumn("Tgl. Sewa");
        tbl.addColumn("Tgl. Tenggat");
        tbl.addColumn("Sub Total");

        jTable_detailForm.setModel(tbl);

        String cari = jTextField_search.getText();
        StringBuilder sql = new StringBuilder("SELECT * FROM v_detailsewa ");
        String newSql = sql.toString().concat(" WHERE status = 'perjalanan' AND v_detailsewa.kd_penyewaan LIKE '%" + cari + "%' ");
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery(newSql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kd_detail_sewa"),
                    res.getString("nama_mobil"),
                    (res.getString("nama_supir") == null) ? "Tidak Ada Supir" : res.getString("nama_supir"),
                    res.getString("tgl_sewa"),
                    res.getString("tgl_tenggat"),
                    res.getString("subtotal")
                });
            }
            jTable_detailForm.setModel(tbl);
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_detailForm = new javax.swing.JTable();
        jLabel_sumbit = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_detailForm.setBackground(new java.awt.Color(238, 218, 222));
        jTable_detailForm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTable_detailForm.setForeground(new java.awt.Color(51, 51, 51));
        jTable_detailForm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Detail", "Nama Mobil", "Tgl. Sewa", "Tgl. Tenggat", "Sub Total"
            }
        ));
        jTable_detailForm.setRowHeight(40);
        jTable_detailForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_detailFormMouseClicked(evt);
            }
        });
        jTable_detailForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_detailFormKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_detailForm);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 880, 300));

        jLabel_sumbit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel_sumbit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sumbit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_sumbit.setText("Submit");
        jLabel_sumbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_sumbitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_sumbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 566, 100, 40));

        jTextField_search.setBackground(new java.awt.Color(255, 217, 217));
        jTextField_search.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextField_search.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_search.setBorder(null);
        jTextField_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchActionPerformed(evt);
            }
        });
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 210, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Form Pengembalian");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Form Pengembalian");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 520, 90));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 820, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(177, 0, 7));
        jLabel6.setText("Kode Transaksi");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 230, 60));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Form Pengembalian");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 330, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 4));
        jLabel1.setPreferredSize(new java.awt.Dimension(1027, 659));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_sumbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sumbitMouseClicked
        String kd_detail_sewa = kode_detail_sewa;

        try {
            Statement Statement = DB.getConnection().createStatement();
            ResultSet res = Statement.executeQuery("SELECT genPengembalianID() AS pengembalianID");
            String kd_pengembalian = "";
            if (res.next()) {
                kd_pengembalian = res.getString("pengembalianID");
            }

            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql, sql1;
            LocalDate tgl_pengembalian = LocalDate.now();
            pop_upTanyaPengembalian tanya = new pop_upTanyaPengembalian(kode_detail_sewa, kd_pengembalian, v);
            tanya.setVisible(true);
            
           
//            int opsi = JOptionPane.showConfirmDialog(null, "Apakah Ada Kerusakan / Pelanggaran ?", "Peringatan", JOptionPane.YES_NO_OPTION);
//            if (opsi == JOptionPane.YES_OPTION) {
//                form_dendaPengembalian frm_denda = new form_dendaPengembalian(kode_detail_sewa, kd_pengembalian, v);
//                frm_denda.setVisible(true);
//                this.dispose();
//            } else if (opsi == JOptionPane.NO_OPTION) {
//            sql = "insert into pengembalian VALUES('" + kd_pengembalian + "','" + kd_detail_sewa + "'"
//                    + ",'" + tgl_pengembalian + "' , 0, 0);";
//            sql1 = "update detail_sewa set status = 'selesai' where kd_detail_sewa = '" + kd_detail_sewa + "'";
//            statement.execute(sql);
//            statement.executeUpdate(sql1);
//            PreparedStatement ps;
//            ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
//            ResultSet result = ps.executeQuery();
//            while (result.next()) {
//                String activity = "Melakukan Pengembalian Transaksi";
//                ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
//                ps.executeUpdate();
//                break;
//            }
//            }
//            pop_upDataberhasil dataudbah = new pop_upDataberhasil();
//            dataudbah.setVisible(true);
//            this.v.generateTablePengembalianMaster();
            this.dispose();

        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }


    }//GEN-LAST:event_jLabel_sumbitMouseClicked

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        getDetailSewa(jTextField_search.getText());

    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable_detailFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_detailFormMouseClicked
        int baris = jTable_detailForm.rowAtPoint(evt.getPoint());
        String kd_detail_sewa = jTable_detailForm.getValueAt(baris, 0).toString();
        kode_detail_sewa = kd_detail_sewa;
//        pop_upPelanggaran pop_up = new pop_upPelanggaran();
//        pop_up.setVisible(true);
    }//GEN-LAST:event_jTable_detailFormMouseClicked

    private void jTable_detailFormKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_detailFormKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_detailFormKeyReleased

    private void jTextField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pengembalianv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pengembalianv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pengembalianv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pengembalianv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_Pembatalan(null, null).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_Pembatalan(null, null).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_Pembatalan(null, null).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_Pembatalan(null, null).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_sumbit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_detailForm;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables

}
