/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pengembalian;

import DB_koneksi.DB;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author sakab
 */
public class Pelanggaran extends javax.swing.JFrame {

    
    /**
     * Creates new form Pelanggaran
     */
    String idDet, idMobil, idSupir;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");

    public Pelanggaran( String kd_detail) {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        

        initComponents();
        
        this.idDet = kd_detail;
        getData();
        
        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_customer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_kdSewa = new javax.swing.JTextField();
        jTextField_gantiRugi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_mobil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_keterangan = new javax.swing.JTextField();
        jButton_simpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(177, 0, 7));
        jLabel9.setText("Form Pelanggaran");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 6, 10, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel1.setText("Kode Penyewaan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jTextField_customer.setEnabled(false);
        jTextField_customer.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(jTextField_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 201, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel2.setText("Biaya Ganti Rugi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel3.setText("Nama Penyewa");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jTextField_kdSewa.setEnabled(false);
        jTextField_kdSewa.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(jTextField_kdSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 201, -1));

        jTextField_gantiRugi.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(jTextField_gantiRugi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 201, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel4.setText("Nama Mobil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jTextField_mobil.setEnabled(false);
        jTextField_mobil.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(jTextField_mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 201, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setText("Keterangan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jTextField_keterangan.setPreferredSize(new java.awt.Dimension(64, 30));
        jPanel1.add(jTextField_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 201, 110));

        jButton_simpan.setBackground(new java.awt.Color(204, 0, 51));
        jButton_simpan.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_simpan.setForeground(new java.awt.Color(255, 255, 255));
        jButton_simpan.setText("Simpan Data");
        jButton_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 106, 40));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 8, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_simpanActionPerformed
        try{
            Statement state = DB.getConnection().createStatement();
            ResultSet res = state.executeQuery("SELECT genPelanggaranID() AS plgID; ");
            String kdPlg = "";
            if(res.next()){
                kdPlg = res.getString("plgID");
            }  
            String idSewa = jTextField_kdSewa.getText();
            
            String gantiRugi = jTextField_gantiRugi.getText();
            String keterangan = jTextField_keterangan.getText();
            String tglPelanggaran = sdf.format(new Date());
            state.executeUpdate("INSERT INTO pelanggaran VALUES('"+ kdPlg +"', '"+ idSewa +"', '" + idMobil + "'," + idSupir + ", '"+ gantiRugi +"', '"+ keterangan +"','"+ tglPelanggaran +"')");
            state.executeUpdate("UPDATE detail_sewa SET tgl_kembali='"+ tglPelanggaran +"', status='selesai' WHERE kd_detail_sewa ='"+ idDet +"' ");
            state.executeUpdate("UPDATE mobil SET status='tersedia' WHERE kd_mobil='"+ idMobil +"' ");
            if(idSupir != null){
                state.executeUpdate("UPDATE supir SET status='bersedia' WHERE kd_supir='"+ idSupir +"'");
            }
            JOptionPane.showMessageDialog(null, "Berhasil Memasukan Data");

        }catch(Exception x){
            JOptionPane.showMessageDialog(null, x);
        }
    }//GEN-LAST:event_jButton_simpanActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    void getData() {
        try{
            Statement state = DB.getConnection().createStatement();
            ResultSet res = state.executeQuery("SELECT * FROM v_pra_pelanggaran WHERE kd_detail_sewa = '"+ idDet +"'");
            if(res.next()){
                jTextField_kdSewa.setText(res.getString("kd_penyewaan"));
                jTextField_mobil.setText(res.getString("nama_mobil"));
                jTextField_customer.setText(res.getString("nama_customer"));
                idMobil = res.getString("kd_mobil");
                idSupir = (res.getString("kd_supir") != null) ? "'" +  res.getString("kd_supir") + "'" : null;
            }
        }catch(Exception x){
            JOptionPane.showMessageDialog(rootPane, x);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggaran(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_customer;
    private javax.swing.JTextField jTextField_gantiRugi;
    private javax.swing.JTextField jTextField_kdSewa;
    private javax.swing.JTextField jTextField_keterangan;
    private javax.swing.JTextField jTextField_mobil;
    // End of variables declaration//GEN-END:variables

    
}
