/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pengembalian;

import rental.Dashboardadmin;
import DB_koneksi.DB;
import functions.pop_upnoData;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakab
 */
public class Pengembalianv2 extends javax.swing.JPanel {

    Dashboardadmin dashboard;

    public Pengembalianv2(Dashboardadmin dashboard) {
        initComponents();
        generateTablePengembalianMaster();
        

        this.dashboard = dashboard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_pengembalianDetail = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_pengembalianMaster = new javax.swing.JTable();
        jTextField_search1 = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(937, 510));
        setPreferredSize(new java.awt.Dimension(937, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_pengembalianDetail.setBackground(new java.awt.Color(238, 218, 222));
        jTable_pengembalianDetail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTable_pengembalianDetail.setForeground(new java.awt.Color(51, 51, 51));
        jTable_pengembalianDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pengembalian", "Nama Mobil", "Tgl. Sewa", "Tgl. Pengembalian", "Denda ", "Keterangan Kerusakan"
            }
        ));
        jTable_pengembalianDetail.setRowHeight(40);
        jTable_pengembalianDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_pengembalianDetailMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_pengembalianDetail);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 1340, 310));

        jTable_pengembalianMaster.setBackground(new java.awt.Color(238, 218, 222));
        jTable_pengembalianMaster.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTable_pengembalianMaster.setForeground(new java.awt.Color(51, 51, 51));
        jTable_pengembalianMaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Transaksi", "Nama Custtomer", "Total Harga", "Tgl. Transaksi"
            }
        ));
        jTable_pengembalianMaster.setRowHeight(40);
        jTable_pengembalianMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_pengembalianMasterMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable_pengembalianMaster);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 1340, 230));

        jTextField_search1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextField_search1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_search1.setBorder(null);
        jTextField_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_search1KeyReleased(evt);
            }
        });
        add(jTextField_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 300, 40));

        btn_tambah.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tambah.setText("Tambah");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, 210, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pengembalian.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 936));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_pengembalianDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_pengembalianDetailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_pengembalianDetailMouseClicked

    private void jTable_pengembalianMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_pengembalianMasterMouseClicked
  int baris = jTable_pengembalianMaster.rowAtPoint(evt.getPoint());
        String kd_penyewaan = jTable_pengembalianMaster.getValueAt(baris, 0).toString();
        generateTablePengembalianDetail(kd_penyewaan);
    }//GEN-LAST:event_jTable_pengembalianMasterMouseClicked

    private void jTextField_search1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_search1KeyReleased
 generateTablePengembalianMaster();
    }//GEN-LAST:event_jTextField_search1KeyReleased

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        // TODO add your handling code here:
         Form_Pengembalianv2 pembatalan = new Form_Pengembalianv2(this);
            pembatalan.setVisible(true);
    }//GEN-LAST:event_btn_tambahMouseClicked

    public void generateTablePengembalianMaster() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Transaksi");
        tbl.addColumn("Nama Customer");
        tbl.addColumn("Total Harga");
        tbl.addColumn("Tgl. Transaksi");
        jTable_pengembalianMaster.setModel(tbl);
        String cari = jTextField_search1.getText();
       
        StringBuilder sql = new StringBuilder("SELECT * FROM v_master_pengembalian WHERE kd_penyewaan LIKE '%" + cari + "%'");
        String newSql = sql.toString();
//        System.out.println(newSql);
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery(newSql);
            while (res.next()) {

                tbl.addRow(new Object[]{
                    res.getString("kd_penyewaan"),
                    res.getString("nama_customer"),
                    res.getString("total_harga"),
                 
                 
                    res.getString("tgl_transaksi")
                });
            }
            jTable_pengembalianMaster.setModel(tbl);
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }

    }

    public void generateTablePengembalianDetail(String kd_penyewaan) {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Pengembalian");
        tbl.addColumn("Nama Mobil");
        tbl.addColumn("Tgl. Sewa");
        tbl.addColumn("Tgl. Pengembalian");
        
        tbl.addColumn("keterangan Kerusakan");
        tbl.addColumn("Denda");
        
        jTable_pengembalianDetail.setModel(tbl);
        StringBuilder sql = new StringBuilder("SELECT * FROM v_pengembalian");
        String newSql = sql.toString().concat(" WHERE v_pengembalian.kd_penyewaan LIKE '%" + kd_penyewaan + "%'");
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery(newSql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kd_pengembalian"),
                    res.getString("nama_mobil"),
                    res.getString("tgl_sewa"),
                    res.getString("tgl_pengembalian"),
                    
                    res.getString("keterangan_kerusakan"),
                        res.getString("total_kerusakan")
      
             
                  
                });
            }
            jTable_pengembalianDetail.setModel(tbl);
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
            
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_pengembalianDetail;
    private javax.swing.JTable jTable_pengembalianMaster;
    private javax.swing.JTextField jTextField_search1;
    // End of variables declaration//GEN-END:variables
}
