/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rental;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import DB_koneksi.DB;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import DB_koneksi.DB;
import java.sql.Statement;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;





/**
 *
 * @author ahmad
 */
public class addDataMobil extends javax.swing.JFrame {

    ArrayList<String> nm_pemilik, kd_pemilik;
    String id;
    /**
     * Creates new form addDataMobil
     */
    public addDataMobil(String id_mobil) {
        initComponents();
        this.setLocationRelativeTo(null);
        getPemilik();
        id = id_mobil;
        
        if (id_mobil != null) {
            getData(id_mobil);
            kodeMobil.setText(id_mobil);
        }
        
    }

    void getData(String id_mobil) {
        try {
          
             Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT pemilik_mobil.nama_pemilik,mobil.* FROM mobil inner join pemilik_mobil ON pemilik_mobil.id_pemilik = mobil.id_pemilik where id_mobil ='"+id_mobil+"'");
            
            while (res.next()) {
               namaMobil.setText(res.getString("nama_mobil"));
                    nopolMobil.setText(res.getString("nopol"));
                    jComboBox_pemilik.setSelectedItem(res.getString("nama_pemilik"));
                    tahun.setText(res.getString("tahun_produksi"));
                   harga.setText(res.getString("harga_perhari"));
//                     res.getString("gambar"),
//                    status.setText(res.getString("nopol"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data tidak ada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namaMobil = new javax.swing.JTextField();
        nopolMobil = new javax.swing.JTextField();
        jComboBox_pemilik = new javax.swing.JComboBox<>();
        tahun = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        saveMobil = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_browse = new javax.swing.JButton();
        jLabel_foto = new javax.swing.JLabel();
        jLabel_file = new javax.swing.JLabel();
        kodeMobil = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton_hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaMobil.setBackground(new java.awt.Color(238, 218, 222));
        namaMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMobilActionPerformed(evt);
            }
        });
        jPanel1.add(namaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, 30));

        nopolMobil.setBackground(new java.awt.Color(238, 218, 222));
        nopolMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolMobilActionPerformed(evt);
            }
        });
        jPanel1.add(nopolMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 30));

        jComboBox_pemilik.setBackground(new java.awt.Color(238, 218, 222));
        jPanel1.add(jComboBox_pemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 200, 30));

        tahun.setBackground(new java.awt.Color(238, 218, 222));
        tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunActionPerformed(evt);
            }
        });
        jPanel1.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 200, 30));

        harga.setBackground(new java.awt.Color(238, 218, 222));
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, 30));

        saveMobil.setBackground(new java.awt.Color(255, 0, 51));
        saveMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saveMobil.setForeground(new java.awt.Color(255, 255, 255));
        saveMobil.setText("Save");
        saveMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMobilActionPerformed(evt);
            }
        });
        jPanel1.add(saveMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Form Mobil");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("No Polisi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Harga Perhari");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tahun Produksi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Foto Mobil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nama Mobil");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nama Pemilik");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jButton_browse.setBackground(new java.awt.Color(255, 0, 0));
        jButton_browse.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_browse.setForeground(new java.awt.Color(255, 255, 255));
        jButton_browse.setText("Browse");
        jButton_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        jLabel_foto.setBackground(new java.awt.Color(238, 218, 222));
        jLabel_foto.setOpaque(true);
        jPanel1.add(jLabel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 170, 120));

        jLabel_file.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_file.setText("##");
        jPanel1.add(jLabel_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        kodeMobil.setBackground(new java.awt.Color(238, 218, 222));
        kodeMobil.setEnabled(false);
        kodeMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeMobilActionPerformed(evt);
            }
        });
        jPanel1.add(kodeMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 200, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kode Mobil");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton_hapus.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaMobilActionPerformed

    private void nopolMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopolMobilActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunActionPerformed

    private void saveMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMobilActionPerformed
        // TODO add your handling code here:
//        String id_mobil = kodeMobil.getText();
        String nama_mobil = namaMobil.getText();
        String nopol = nopolMobil.getText();
        String pemilik = kd_pemilik.get(jComboBox_pemilik.getSelectedIndex());
        String tahun_produksi = tahun.getText();
        String harga_perhari = harga.getText();
//        String gambar = gambarMobil.getText();
//        String status = statusMobil.getText();

        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql;
            if (id != null) {
                 sql = "UPDATE mobil SET nama_mobil = '" +namaMobil.getText()+"', nopol = '"+nopolMobil.getText()+"',tahun_produksi = '"+tahun.getText()+"',id_pemilik = '"+pemilik+"',harga_perhari = '"+harga.getText()+"' WHERE mobil.id_mobil = '"+kodeMobil.getText()+"'";
            }else{
            sql = "insert into mobil VALUES(null,'" + nama_mobil + "', '" + nopol + "', '" +pemilik + "','" + tahun_produksi + "','" + harga_perhari + "', null, 'tersedia');"; }
            statement.executeUpdate(sql);
            statement.close();
            JOptionPane.showMessageDialog(null, "data berhasil di SIMPAN");
            this.dispose();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "data gagal di SIMPAN");
        }
    }//GEN-LAST:event_saveMobilActionPerformed

    private void jButton_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browseActionPerformed
        // TODO add your handling code here:
       JFileChooser file = new JFileChooser();
       file.setCurrentDirectory(new File(System.getProperty("user.home")));
       FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png","jpeg");
       file.addChoosableFileFilter(filter);
       int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabel_file.setText(path);
            jLabel_foto.setIcon(resizeImage(path));
            
        }
        else if(result == JFileChooser.CANCEL_OPTION ){
            System.out.println("No File");
        }
       
    }//GEN-LAST:event_jButton_browseActionPerformed

    private void kodeMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeMobilActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:
        try {
            if (id != null) {
                Statement statement = (Statement) DB.getConnection().createStatement();
                String sql;
                sql = "DELETE FROM mobil where id_mobil = '"+kodeMobil.getText()+"'";
                java.sql.Connection conn = (Connection) DB.getConnection();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this,"Data berhasil dihapus"); 
                this.dispose();
            } else {
                namaMobil.setText(null);
                nopolMobil.setText(null);
                jComboBox_pemilik.setSelectedItem(this);
                tahun.setText(null);
                harga.setText(null);
                JOptionPane.showMessageDialog(this,"Data berhasil dikosongkan"); 
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_hapusActionPerformed

    public ImageIcon resizeImage(String imagePath){
        ImageIcon imgIcon = new ImageIcon(imagePath);
        Image img = imgIcon.getImage();
        Image newImg = img.getScaledInstance(jLabel_foto.getWidth(), jLabel_foto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    void getPemilik(){
        nm_pemilik = new ArrayList<String>();
        kd_pemilik = new ArrayList<String>();
        try{
            Statement state = DB.getConnection().createStatement();
            ResultSet res = state.executeQuery("select id_pemilik, nama_pemilik from pemilik_mobil");
            while(res.next()){
                jComboBox_pemilik.addItem(res.getString("nama_pemilik"));
                kd_pemilik.add(res.getString("id_pemilik"));
            }

        }catch(Exception x){
            JOptionPane.showMessageDialog(rootPane, x);
        
        }   
    }
    /**
     * @param args the command line arguments
     */
   
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addDataMobil(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton_browse;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JComboBox<String> jComboBox_pemilik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_file;
    private javax.swing.JLabel jLabel_foto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kodeMobil;
    private javax.swing.JTextField namaMobil;
    private javax.swing.JTextField nopolMobil;
    private javax.swing.JButton saveMobil;
    private javax.swing.JTextField tahun;
    // End of variables declaration//GEN-END:variables

    private String selectImage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void displayImage(int width, int height, String imagePath, JLabel jLabel_foto) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
  
