/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rental;

import History.History;
import Mobil.Mobil;
import Mobil.Mobil;
import PemilikMobil.dataPemilik;
import Penyewaan.Sewa;
import Sopir.Sopir;
import dataAdmin.User;

import dataCustomer.Customer;
import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;
import History.dataLog;
import Pengembalian.Pengembalian;

/**
 *
 * @author sakab
 */
public class Dashboard extends javax.swing.JFrame {
    private JPanel Mobil;
    /**
     * Creates new form Dashboard
     */
    
     //      border
    Border red_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.red);
    Border empty_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(254, 254, 254));
    public Dashboard() {
        
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
        
        
        //        set border di menu item
        jLabel_dashboard.setBorder(empty_border);
        jLabel_Sewa.setBorder(empty_border);
        jLabel_Pengembalian.setBorder(empty_border);
      
        //        menu item
        displayImage(jLabel_icon_dashboard.getWidth(), jLabel_icon_dashboard.getHeight(), "../images/icon_menu/icon_dashboard.png", jLabel_icon_dashboard);
        displayImage(jLabel_icon_sewa.getWidth(), jLabel_icon_sewa.getHeight(), "../images/icon_menu/sewa.png", jLabel_icon_sewa);
        displayImage(jLabel_icon_pengembalian.getWidth(), jLabel_icon_pengembalian.getHeight(), "../images/icon_menu/pengembalian.png", jLabel_icon_pengembalian);
        displayImage(jLabel_icon_data_cust.getWidth(), jLabel_icon_data_cust.getHeight(), "../images/icon_menu/cust.png", jLabel_icon_data_cust);
        
        Date date = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
        jLabel_tgl.setText(tgl.format(date));
        
        jPanel_body.add(new dashboardAdmin());
        jPanel_body.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_tgl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_Sewa = new javax.swing.JLabel();
        jLabel_Pengembalian = new javax.swing.JLabel();
        jLabel_dashboard = new javax.swing.JLabel();
        jLabel_icon_pengembalian = new javax.swing.JLabel();
        jLabel_icon_sewa = new javax.swing.JLabel();
        jLabel_icon_dashboard = new javax.swing.JLabel();
        jLabel_Keluar2 = new javax.swing.JLabel();
        jLabel_dataCustomer = new javax.swing.JLabel();
        jLabel_icon_data_cust = new javax.swing.JLabel();
        jPanel_body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(177, 16, 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 100));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel_tgl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel_tgl.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\msi\\NetBeansProjects\\RentalMobil\\src\\images\\Logo Autorentals 2.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hello,");

        admin.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Hello,");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(jLabel_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(admin))
                            .addComponent(jLabel_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));

        jLabel_Sewa.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_Sewa.setText("Penyewaan");
        jLabel_Sewa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Sewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SewaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_SewaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_SewaMouseExited(evt);
            }
        });

        jLabel_Pengembalian.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_Pengembalian.setText("Pengembalian");
        jLabel_Pengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_PengembalianMouseExited(evt);
            }
        });

        jLabel_dashboard.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dashboard.setText("Dashboard");
        jLabel_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseExited(evt);
            }
        });

        jLabel_icon_pengembalian.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_pengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_pengembalian.setOpaque(true);

        jLabel_icon_sewa.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_sewa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_sewa.setOpaque(true);

        jLabel_icon_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_dashboard.setOpaque(true);

        jLabel_Keluar2.setBackground(new java.awt.Color(204, 0, 51));
        jLabel_Keluar2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_Keluar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Keluar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Keluar2.setText("Keluar");
        jLabel_Keluar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Keluar2.setOpaque(true);
        jLabel_Keluar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Keluar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Keluar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Keluar2MouseExited(evt);
            }
        });

        jLabel_dataCustomer.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dataCustomer.setText("Data Customer");
        jLabel_dataCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseExited(evt);
            }
        });

        jLabel_icon_data_cust.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_data_cust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_data_cust.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_icon_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Pengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Sewa)
                                    .addComponent(jLabel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 34, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_icon_data_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Keluar2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_dataCustomer))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dataCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_data_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(jLabel_Keluar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel_body.setBackground(new java.awt.Color(243, 245, 250));
        jPanel_body.setMaximumSize(new java.awt.Dimension(811, 534));
        jPanel_body.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayImage(int width, int height, String image_path, JLabel label) {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(image_path));
        Image image = imageIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);

        label.setIcon(new ImageIcon(image));

    }
    
    private void jLabel_SewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SewaMouseClicked
       Sewa sewa = new Sewa();
        jPanel_body.removeAll();
        jPanel_body.add(sewa);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_SewaMouseClicked

    private void jLabel_SewaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SewaMouseEntered
        // TODO add your handling code here:
        jLabel_Sewa.setBorder(red_border);
    }//GEN-LAST:event_jLabel_SewaMouseEntered

    private void jLabel_SewaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SewaMouseExited
        // TODO add your handling code here:
        jLabel_Sewa.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_SewaMouseExited

    private void jLabel_PengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PengembalianMouseClicked
        // TODO add your handling code here:
        Pengembalian kembali = new Pengembalian(this);
        jPanel_body.removeAll();
        jPanel_body.add(kembali);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_PengembalianMouseClicked

    private void jLabel_PengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PengembalianMouseEntered
        // TODO add your handling code here:
        jLabel_Pengembalian.setBorder(red_border);
    }//GEN-LAST:event_jLabel_PengembalianMouseEntered

    private void jLabel_PengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PengembalianMouseExited
        // TODO add your handling code here:
        jLabel_Pengembalian.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_PengembalianMouseExited

    private void jLabel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseClicked
       dashboardAdmin dashboard = new dashboardAdmin();
       jPanel_body.removeAll();
       jPanel_body.add(dashboard);
       jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dashboardMouseClicked

    private void jLabel_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseEntered
        // TODO add your handling code here:
        jLabel_dashboard.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dashboardMouseEntered

    private void jLabel_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseExited
        // TODO add your handling code here:
        jLabel_dashboard.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dashboardMouseExited

    private void jLabel_Keluar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Keluar2MouseClicked
       login front = new login();
      this.dispose();
       front.setVisible(true);
    }//GEN-LAST:event_jLabel_Keluar2MouseClicked

    private void jLabel_Keluar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Keluar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Keluar2MouseEntered

    private void jLabel_Keluar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Keluar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Keluar2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel_dataCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseExited
        // TODO add your handling code here:
        jLabel_dataCustomer.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataCustomerMouseExited

    private void jLabel_dataCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseEntered
        // TODO add your handling code here:
        jLabel_dataCustomer.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataCustomerMouseEntered

    private void jLabel_dataCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseClicked

        Customer cust = new Customer();
        jPanel_body.removeAll();
        jPanel_body.add(cust);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataCustomerMouseClicked

    public JPanel getJpanelBody(){
        return jPanel_body;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Keluar2;
    private javax.swing.JLabel jLabel_Pengembalian;
    private javax.swing.JLabel jLabel_Sewa;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_dataCustomer;
    private javax.swing.JLabel jLabel_icon_dashboard;
    private javax.swing.JLabel jLabel_icon_data_cust;
    private javax.swing.JLabel jLabel_icon_pengembalian;
    private javax.swing.JLabel jLabel_icon_sewa;
    private javax.swing.JLabel jLabel_tgl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_body;
    // End of variables declaration//GEN-END:variables
}
