/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rental;


import Pelunasan.datamaster;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.Border;
import Pembatalan.Pembatalanv2;
import Pengembalian.Pengembalianv2;
import Penyewaan.Penyewaanv3;
import dataCustomer.Custv2;

/**
 *
 * @author sakab
 */
public class Dashboardadmin extends javax.swing.JFrame {

    private JPanel Mobil;
    public String id_user = login.idUser;
    /**
     * Creates new form Dashboard
     */

    //      border
    Border red_border = BorderFactory.createMatteBorder(0, 0, 4, 0, Color.red);
    Border empty_border = BorderFactory.createMatteBorder(0, 0, 0, 0,Color.white);

    public Dashboardadmin() {

        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);

        //        set border di menu item
//        jLabel_dashboard.setBorder(empty_border);
        jLabel_penyewaan.setBorder(empty_border);
        jLabel_pengembalian.setBorder(empty_border);

//        //        menu item
//        displayImage(jLabel_icon_dashboard.getWidth(), jLabel_icon_dashboard.getHeight(), "../images/icon_menu/icon_dashboard.png", jLabel_icon_dashboard);
//        displayImage(jLabel_icon_sewa.getWidth(), jLabel_icon_sewa.getHeight(), "../images/icon_menu/sewa.png", jLabel_icon_sewa);
//        displayImage(jLabel_icon_pengembalian.getWidth(), jLabel_icon_pengembalian.getHeight(), "../images/icon_menu/pengembalian.png", jLabel_icon_pengembalian);
//        displayImage(jLabel_icon_data_cust.getWidth(), jLabel_icon_data_cust.getHeight(), "../images/icon_menu/cust.png", jLabel_icon_data_cust);

        Date date = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
        jLabel_tgl.setText(tgl.format(date));

        jPanel_body.add(new Penyewaanv3(this));
        jPanel_body.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_pelunasan = new javax.swing.JLabel();
        jPanel_body = new javax.swing.JPanel();
        jLabel_penyewaan = new javax.swing.JLabel();
        jLabel_pengembalian = new javax.swing.JLabel();
        jLabel_pembatalan = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jLabel_tgl = new javax.swing.JLabel();
        jLabel_cust = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_pelunasan.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel_pelunasan.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_pelunasan.setText("Pelunasan");
        jLabel_pelunasan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_pelunasanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_pelunasanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_pelunasanMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_pelunasan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 240, 40));

        jPanel_body.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_body.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 1460, 930));

        jLabel_penyewaan.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel_penyewaan.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_penyewaan.setText("Penyewaan");
        jLabel_penyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_penyewaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_penyewaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_penyewaanMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_penyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 240, 40));

        jLabel_pengembalian.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel_pengembalian.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_pengembalian.setText("Pengembalian");
        jLabel_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_pengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_pengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_pengembalianMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 240, 40));

        jLabel_pembatalan.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel_pembatalan.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_pembatalan.setText("Pembatalan");
        jLabel_pembatalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_pembatalanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_pembatalanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_pembatalanMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_pembatalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 240, 40));

        exit.setBackground(new java.awt.Color(204, 0, 51));
        exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 0, 20, -1));

        jLabel_logout.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel_logout.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logout.setText("Keluar");
        jLabel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 917, 200, 50));

        jLabel_tgl.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_tgl.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_tgl.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_tgl.setText("jLabel1");
        getContentPane().add(jLabel_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 500, -1));

        jLabel_cust.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel_cust.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_cust.setText("Customer");
        jLabel_cust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_custMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_custMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_custMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_cust, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 240, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_penyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_penyewaanMouseClicked
        // TODO add your handling code here:
        Penyewaanv3 sewa = new Penyewaanv3(this);
        jPanel_body.removeAll();
        jPanel_body.add(sewa);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_penyewaanMouseClicked

    private void jLabel_penyewaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_penyewaanMouseEntered
        // TODO add your handling code here:
        jLabel_penyewaan.setBorder(red_border);
    }//GEN-LAST:event_jLabel_penyewaanMouseEntered

    private void jLabel_penyewaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_penyewaanMouseExited
        // TODO add your handling code here:
        jLabel_penyewaan.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_penyewaanMouseExited

    private void jLabel_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pengembalianMouseClicked
        // TODO add your handling code here:
        Pengembalianv2 kembali = new Pengembalianv2(this);
        jPanel_body.removeAll();
        jPanel_body.add(kembali);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_pengembalianMouseClicked

    private void jLabel_pengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pengembalianMouseEntered
        // TODO add your handling code here:
        jLabel_pengembalian.setBorder(red_border);
    }//GEN-LAST:event_jLabel_pengembalianMouseEntered

    private void jLabel_pengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pengembalianMouseExited
        // TODO add your handling code here:
        jLabel_pengembalian.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_pengembalianMouseExited

    private void jLabel_pembatalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pembatalanMouseClicked
        // TODO add your handling code here:
        Pembatalanv2 pembatalan = new Pembatalanv2();
        jPanel_body.removeAll();
        jPanel_body.add(pembatalan);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_pembatalanMouseClicked

    private void jLabel_pembatalanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pembatalanMouseEntered
        // TODO add your handling code here:
        jLabel_pembatalan.setBorder(red_border);
    }//GEN-LAST:event_jLabel_pembatalanMouseEntered

    private void jLabel_pembatalanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pembatalanMouseExited
        // TODO add your handling code here:
        jLabel_pembatalan.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_pembatalanMouseExited

    private void jLabel_pelunasanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pelunasanMouseClicked
        // TODO add your handling code here:
        datamaster cust = new datamaster();
        jPanel_body.removeAll();
        jPanel_body.add(cust);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_pelunasanMouseClicked

    private void jLabel_pelunasanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pelunasanMouseEntered
        // TODO add your handling code here:
        jLabel_pelunasan.setBorder(red_border);
    }//GEN-LAST:event_jLabel_pelunasanMouseEntered

    private void jLabel_pelunasanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_pelunasanMouseExited
        // TODO add your handling code here:
        jLabel_pelunasan.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_pelunasanMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
        login front = new login();
        this.dispose();
        front.setVisible(true);
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    private void jLabel_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel_logoutMouseEntered

    private void jLabel_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel_logoutMouseExited

    private void jLabel_custMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_custMouseClicked
        // TODO add your handling code here:
        Custv2 customer = new Custv2();
        jPanel_body.removeAll();
        jPanel_body.add(customer);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_custMouseClicked

    private void jLabel_custMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_custMouseEntered
        // TODO add your handling code here:
        jLabel_cust.setBorder(red_border);
    }//GEN-LAST:event_jLabel_custMouseEntered

    private void jLabel_custMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_custMouseExited
        // TODO add your handling code here:
         jLabel_cust.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_custMouseExited



    
    public JPanel getJpanelBody() {
        return jPanel_body;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboardadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboardadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboardadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboardadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboardadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_cust;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JLabel jLabel_pelunasan;
    private javax.swing.JLabel jLabel_pembatalan;
    private javax.swing.JLabel jLabel_pengembalian;
    private javax.swing.JLabel jLabel_penyewaan;
    private javax.swing.JLabel jLabel_tgl;
    private javax.swing.JPanel jPanel_body;
    // End of variables declaration//GEN-END:variables
}
