/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rental;

import DB_koneksi.DB;
import Mobil.Form_Mobilv2;
import functions.pop_upExcelReport;
import functions.pop_upLoginGagal;
import functions.pop_up_rfidv2;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import owner.dashboardOwnerV1;

/**
 *
 * @author sakab
 */
public class login extends javax.swing.JFrame {

    public static String namaUser;
    public static String idUser;
    int i = 1;

    /**
     * Creates new form login
     */
    public login() {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//                this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();

//        ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
//        ini images
//        jLabel_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/bglogin1.png")));
////        System.getProperty("user.dir");
//        System.getProperty("user.dir").get"../images/bglogin1.png";
    }

    public void customInit() {

        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpassword = new javax.swing.JPasswordField();
        Jusername = new javax.swing.JTextField();
        exit = new javax.swing.JLabel();
        jCheckBox = new javax.swing.JCheckBox();
        field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpassword.setBackground(new java.awt.Color(238, 218, 222));
        Jpassword.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Jpassword.setForeground(new java.awt.Color(0, 0, 0));
        Jpassword.setBorder(null);
        Jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 590, 500, 50));

        Jusername.setBackground(new java.awt.Color(238, 218, 222));
        Jusername.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Jusername.setForeground(new java.awt.Color(0, 0, 0));
        Jusername.setBorder(null);
        Jusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JusernameActionPerformed(evt);
            }
        });
        getContentPane().add(Jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 440, 500, 50));

        exit.setBackground(new java.awt.Color(204, 0, 51));
        exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 51));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 0, 20, -1));

        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 670, 30, 30));

        field.setBackground(new java.awt.Color(255, 255, 255));
        field.setForeground(new java.awt.Color(0, 0, 0));
        field.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                fieldInputMethodTextChanged(evt);
            }
        });
        field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldKeyTyped(evt);
            }
        });
        getContentPane().add(field, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 730, 0, 50));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login With RFID");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 730, 390, 70));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 830, 390, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loginv4.jpg"))); // NOI18N
        jLabel1.setText("Lo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JusernameActionPerformed

    private void JpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpasswordActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        // untuk melihat password
        if (jCheckBox.isSelected()) {
            Jpassword.setEchoChar((char) 0);
        } else {
            Jpassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        String username = Jusername.getText();
        String password = String.valueOf(Jpassword.getPassword());

        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * FROM `user` WHERE `username` = ? AND `password`= ?";

//        check isian
        if (username.trim().toLowerCase().equals("username") || password.trim().toLowerCase().equals("password")) {
            JOptionPane.showMessageDialog(null, "Username atau Password salah");
        } else {
            try {
                ps = DB.getConnection().prepareStatement(query);
                ps.setString(1, username);
                ps.setString(2, password);
                rs = ps.executeQuery();

                if (rs.next()) {
                    idUser = rs.getString("kd_user");
                    namaUser = rs.getString("nama_lengkap");
                    if (rs.getString("role").equals("Owner")) {
                         String activity = "Login Owner";
                        ps = DB.getConnection().prepareStatement("CALL createLog('" + idUser + "','" + activity + "');");
                        ps.executeUpdate();
                        dashboardOwnerV1 frm_dsh = new dashboardOwnerV1();
                        frm_dsh.setVisible(true);
                         
                    }
                    if (rs.getString("role").equals("Admin")) {
                         String activity = "Login Admin";
                        ps = DB.getConnection().prepareStatement("CALL createLog('" + idUser + "','" + activity + "');");
                        ps.executeUpdate();
                        Dashboardadmin frm_dsh = new Dashboardadmin();
                        frm_dsh.setVisible(true);
                       
                    }
                    this.dispose();
                } else {
                    pop_upLoginGagal error = new pop_upLoginGagal();
                    error.setVisible(true);
                    Jusername.setText(null);
                    Jpassword.setText(null);
                }
            } catch (SQLException ex) {
                 System.out.println(ex.getMessage());
                
            }

        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        field.setText("");
        i = 1;
        field.requestFocusInWindow();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldKeyTyped

    }//GEN-LAST:event_fieldKeyTyped

    // Create a JDialog from the JOptionPane
    // Show the dialog

    private void fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldKeyReleased
        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * FROM `user` WHERE `rfid` = ?";
        String RFID = field.getText();
        try {
            ps = DB.getConnection().prepareStatement(query);
            ps.setString(1, RFID);
            rs = ps.executeQuery();

            if (rs.next()) {
                idUser = rs.getString("kd_user");
                namaUser = rs.getString("nama_lengkap");
                if (rs.getString("role").equals("Owner")) {
                    dashboardOwnerV1 frm_dsh = new dashboardOwnerV1();
                    frm_dsh.setVisible(true);
                }
                if (rs.getString("role").equals("Admin")) {
                    Dashboardadmin frm_dsh = new Dashboardadmin();
                    frm_dsh.setVisible(true);
                }
                this.dispose();
            } else {
                if (i > 10) {
                    try {
                        pop_up_rfidv2 pop = new pop_up_rfidv2();
                        pop.setVisible(true);
                        jLabel2MouseClicked(null);
                        return;
//                        jLabel2MouseClicked(null);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
            i += 1;

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_fieldKeyReleased

    private void fieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_fieldInputMethodTextChanged
//        Form_Mobilv2 mobil = new Form_Mobilv2("", null);
//        mobil.setVisible(true);
    }//GEN-LAST:event_fieldInputMethodTextChanged

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new login().setVisible(true);
                login log = new login();

                log.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Jpassword;
    private javax.swing.JTextField Jusername;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField field;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
