/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rental;

import DB_koneksi.DB;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author artob
 */
public class PenyewaanMobil extends javax.swing.JPanel {

    ArrayList<String> idMobil;
    
    public PenyewaanMobil() {
        initComponents();
        setupTable();
        jComboBox_Mobil.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e) {
                JOptionPane.showMessageDialog(null, "Item changed");
                String id_mobil = idMobil.get(jComboBox_Mobil.getSelectedIndex());
                try {
                    Statement state = DB.getConnection().createStatement();
                    ResultSet res;
                    res = state.executeQuery("SELECT harga_perhari FROM mobil WHERE id_mobil='"+ id_mobil+"'");
                    int harga_perhari = res.getInt("harga_perhari");
                    jTextField_harga_perhari.setText(String.valueOf(harga_perhari));
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex);
                }
            }   
        });
    }
    
    void setupTable(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Mobil");
        tbl.addColumn("Nama Mobil");
        tbl.addColumn("Harga Perhari");
        tbl.addColumn("Jml Hari");
        tbl.addColumn("Subtotal");
        
        jTable1.setModel(tbl);
    }
    
    void getMobil(){
        try{
            Statement state = DB.getConnection().createStatement();
            ResultSet res = state.executeQuery("SELECT id_mobil, nama_mobil, nopol FROM mobil WHERE status='tersedia'");
            while(res.next()){
                jComboBox_Mobil.addItem(res.getString("nama_mobil") + " - " + res.getString("nopol"));
                idMobil.add(res.getString("id_mobil"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_penyewa1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox_Mobil = new javax.swing.JComboBox<>();
        jTextField_harga_perhari = new javax.swing.JTextField();
        jSpinner_hari = new javax.swing.JSpinner();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel_hargasewa = new javax.swing.JLabel();
        jButton_tambah = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField_penyewa1.setText("Nama Penyewa");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_harga_perhari.setEditable(false);
        jTextField_harga_perhari.setText("harga_perhari");

        jSpinner_hari.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner_hari.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_hariStateChanged(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        jLabel_hargasewa.setText("Harga sewa");

        jButton_tambah.setText("Tambah");
        jButton_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_penyewa1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_Mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_harga_perhari, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addComponent(jButton_tambah))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel_hargasewa)))
                .addContainerGap(575, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_penyewa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel_hargasewa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_Mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_harga_perhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jButton_tambah)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSpinner_hariStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_hariStateChanged
       int jml_hari = Integer.parseInt(jSpinner_hari.getValue().toString());
       int harga_sewa = Integer.parseInt(jTextField_harga_perhari.getText()) * jml_hari;
       jLabel_hargasewa.setText(String.valueOf(harga_sewa));
    }//GEN-LAST:event_jSpinner_hariStateChanged

    private void jButton_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambahActionPerformed
        String id_mobil = idMobil.get(jComboBox_Mobil.getSelectedIndex());
        String nama_mobil = jComboBox_Mobil.getName();
        String harga_perhari = jTextField_harga_perhari.getText();
        String jml_hari = jSpinner_hari.getValue().toString();
        String subttl = jLabel_hargasewa.getText();
        String[] data = { id_mobil, nama_mobil, harga_perhari, jml_hari, subttl };
        DefaultTableModel tbl = (DefaultTableModel) jTable1.getModel();
        tbl.addRow(data);
    }//GEN-LAST:event_jButton_tambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_tambah;
    private javax.swing.JComboBox<String> jComboBox_Mobil;
    private javax.swing.JLabel jLabel_hargasewa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner_hari;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_harga_perhari;
    private javax.swing.JTextField jTextField_penyewa1;
    // End of variables declaration//GEN-END:variables
}
