/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sopir;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import DB_koneksi.DB;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author sakab
 */
public class formSopir extends javax.swing.JFrame {

    String id;
    Sopir sopir;
    /**
     * Creates new form FormSopir
     */
    public formSopir(String id_supir,Sopir sopir) {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        this.sopir = sopir;
        this.setLocationRelativeTo(null);
        id = id_supir;
        
        if (id_supir != null) {
            getData(id_supir);
            kodeSopir.setText(id_supir);
        }
        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveMobil = new javax.swing.JButton();
        jButton_hapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kodeSopir = new javax.swing.JTextField();
        namaSopir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        noTelp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        saveSopir = new javax.swing.JButton();
        jButton_hapus1 = new javax.swing.JButton();
        noKtp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        saveMobil.setBackground(new java.awt.Color(255, 0, 51));
        saveMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saveMobil.setForeground(new java.awt.Color(255, 255, 255));
        saveMobil.setText("Save");
        saveMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMobilActionPerformed(evt);
            }
        });

        jButton_hapus.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 5, true));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Form Sopir");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kode Sopir");

        kodeSopir.setBackground(new java.awt.Color(238, 218, 222));
        kodeSopir.setForeground(new java.awt.Color(0, 0, 0));
        kodeSopir.setEnabled(false);
        kodeSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeSopirActionPerformed(evt);
            }
        });

        namaSopir.setBackground(new java.awt.Color(238, 218, 222));
        namaSopir.setForeground(new java.awt.Color(0, 0, 0));
        namaSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSopirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama Sopir");

        alamat.setBackground(new java.awt.Color(238, 218, 222));
        alamat.setForeground(new java.awt.Color(0, 0, 0));
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Alamat");

        noTelp.setBackground(new java.awt.Color(238, 218, 222));
        noTelp.setForeground(new java.awt.Color(0, 0, 0));
        noTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("No.Telp");

        saveSopir.setBackground(new java.awt.Color(255, 0, 51));
        saveSopir.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saveSopir.setForeground(new java.awt.Color(255, 255, 255));
        saveSopir.setText("Save");
        saveSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSopirActionPerformed(evt);
            }
        });

        jButton_hapus1.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_hapus1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus1.setText("Hapus");
        jButton_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapus1ActionPerformed(evt);
            }
        });

        noKtp.setBackground(new java.awt.Color(238, 218, 222));
        noKtp.setForeground(new java.awt.Color(0, 0, 0));
        noKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noKtpActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("No.Ktp");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(saveSopir)
                        .addGap(38, 38, 38)
                        .addComponent(jButton_hapus1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(kodeSopir, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                                    .addComponent(namaSopir)
                                    .addComponent(noTelp)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel9))
                            .addComponent(noKtp)
                            .addComponent(alamat))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel9)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kodeSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noKtp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveSopir)
                    .addComponent(jButton_hapus1))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getData(String id_supir) {
        try {
          
             Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM supir  where kd_supir ='"+id_supir+"'");
            
            while (res.next()) {
               namaSopir.setText(res.getString("nama_supir"));
               noKtp.setText(res.getString("no_ktp"));
               noTelp.setText(res.getString("no_telp"));
               alamat.setText(res.getString("alamat"));
//                     res.getString("gambar"),
//                    status.setText(res.getString("nopol"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data tidak ada");
        }
    }
    private void kodeSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeSopirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeSopirActionPerformed

    private void namaSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSopirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaSopirActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void noTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpActionPerformed

    private void saveMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMobilActionPerformed
        
    }//GEN-LAST:event_saveMobilActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_hapusActionPerformed

    private void saveSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSopirActionPerformed
        // TODO add your handling code here:
        //        String id_mobil = kodeMobil.getText();
        String nama_supir = namaSopir.getText();
        String no_ktp = noKtp.getText();
        String no_tlp = noTelp.getText();
        String Alamat = alamat.getText();
        String num = kodeSopir.getText();
        
        //        String gambar = gambarMobil.getText();
        //        String status = statusMobil.getText();

        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql;
            if (id != null) {
                sql = "UPDATE supir SET nama_supir = '" +namaSopir.getText()+"', no_ktp = '"+noKtp.getText()+"',no_telp = '"+noTelp.getText()+"',alamat = '"+alamat.getText()+"' WHERE kd_supir = '"+kodeSopir.getText()+"'";
                JOptionPane.showMessageDialog(null, "data berhasil di Ubah");
            }else{
                ResultSet res = statement.executeQuery("SELECT genSupirID() AS supirID");
                String kdSupir = ""; 
                if(res.next()){
                    kdSupir = res.getString("supirID");
                }
                sql = "insert into supir VALUES('"+kdSupir+"','" + nama_supir + "', '" + no_ktp + "', '" +no_tlp + "','" + Alamat +"','bersedia');"; 
                JOptionPane.showMessageDialog(null, "data berhasil di SIMPAN");
            }
            statement.executeUpdate(sql);
            statement.close();
            sopir.datatable();
            
            this.dispose();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "data gagal di SIMPAN");
        }
    }//GEN-LAST:event_saveSopirActionPerformed

    private void jButton_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapus1ActionPerformed
        // TODO add your handling code here:
        try {
            if (id != null) {
                Statement statement = (Statement) DB.getConnection().createStatement();
                String sql;
                if (JOptionPane.showConfirmDialog(null,"Yakin ingin menghapus ?","Pesan",JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                     sql = "DELETE FROM supir where kd_supir = '"+kodeSopir.getText()+"'";
                    java.sql.Connection conn = (Connection) DB.getConnection();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(this,"Data berhasil dihapus");
                    sopir.datatable();
                    this.dispose();
                }
               
            } else {
                namaSopir.setText(null);
                noKtp.setText(null);
                alamat.setText(null);
                noTelp.setText(null);
                JOptionPane.showMessageDialog(this,"Data berhasil dikosongkan");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_hapus1ActionPerformed

    private void noKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noKtpActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formSopir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formSopir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formSopir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formSopir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formSopir(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JButton jButton_hapus1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kodeSopir;
    private javax.swing.JTextField namaSopir;
    private javax.swing.JTextField noKtp;
    private javax.swing.JTextField noTelp;
    private javax.swing.JButton saveMobil;
    private javax.swing.JButton saveSopir;
    // End of variables declaration//GEN-END:variables
}
