/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Sopir;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import DB_koneksi.DB;
import Mobil.Form_Mobilv2;
import functions.pop_upClear;
import functions.pop_upDataGagal;
import functions.pop_upDataberhasil;
import functions.pop_upRequired;
import functions.pop_upTanyaClear;
import functions.pop_upnoData;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sakab
 */
public class formSopirv2 extends javax.swing.JFrame {

    String id;
    Sopirv2 sopir;

    /**
     * Creates new form FormSopir
     */
    public formSopirv2(String id_supir, Sopirv2 sopir) {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        this.sopir = sopir;
        jScrollPane1.setBorder(null);
        this.setLocationRelativeTo(null);
        id = id_supir;

        if (id_supir != null) {
            getData(id_supir);
            kodeSopir.setText(id_supir);
        }
        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveMobil = new javax.swing.JButton();
        jButton_hapus = new javax.swing.JButton();
        kodeSopir = new javax.swing.JTextField();
        namaSopir = new javax.swing.JTextField();
        noTelp = new javax.swing.JTextField();
        noKtp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        saveSopir = new javax.swing.JLabel();
        jButton_hapus1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        saveMobil.setBackground(new java.awt.Color(255, 0, 51));
        saveMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saveMobil.setForeground(new java.awt.Color(255, 255, 255));
        saveMobil.setText("Save");
        saveMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMobilActionPerformed(evt);
            }
        });

        jButton_hapus.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kodeSopir.setBackground(new java.awt.Color(238, 218, 222));
        kodeSopir.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        kodeSopir.setEnabled(false);
        kodeSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeSopirActionPerformed(evt);
            }
        });
        getContentPane().add(kodeSopir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 340, 40));

        namaSopir.setBackground(new java.awt.Color(238, 218, 222));
        namaSopir.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        namaSopir.setBorder(null);
        namaSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaSopirActionPerformed(evt);
            }
        });
        getContentPane().add(namaSopir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 320, 30));

        noTelp.setBackground(new java.awt.Color(238, 218, 222));
        noTelp.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        noTelp.setBorder(null);
        getContentPane().add(noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 310, 30));

        noKtp.setBackground(new java.awt.Color(238, 218, 222));
        noKtp.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        noKtp.setBorder(null);
        noKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noKtpActionPerformed(evt);
            }
        });
        getContentPane().add(noKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 320, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        saveSopir.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        saveSopir.setForeground(new java.awt.Color(255, 255, 255));
        saveSopir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveSopir.setText("Simpan");
        saveSopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveSopirMouseClicked(evt);
            }
        });
        getContentPane().add(saveSopir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 120, 50));

        jButton_hapus1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton_hapus1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_hapus1.setText("Reset");
        jButton_hapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_hapus1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 110, 50));

        alamat.setBackground(new java.awt.Color(238, 218, 222));
        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        alamat.setRows(5);
        alamat.setBorder(null);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 530, 140));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(177, 0, 7));
        jLabel2.setText("Data Sopir");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 220, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modal_supirv2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -1, 1040, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getData(String id_supir) {
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM supir  where kd_supir ='" + id_supir + "'");

            while (res.next()) {
                namaSopir.setText(res.getString("nama_supir"));
                noKtp.setText(res.getString("no_ktp"));
                noTelp.setText(res.getString("no_telp"));
                alamat.setText(res.getString("alamat"));
//                     res.getString("gambar"),
//                    status.setText(res.getString("nopol"));
            }
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }
    private void saveMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMobilActionPerformed

    }//GEN-LAST:event_saveMobilActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton_hapusActionPerformed

    private void kodeSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeSopirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeSopirActionPerformed

    private void namaSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaSopirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaSopirActionPerformed

    private void noKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noKtpActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void saveSopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveSopirMouseClicked
        // TODO add your handling code here:
        String nama_supir = namaSopir.getText();
        String no_ktp = noKtp.getText();
        String no_tlp = noTelp.getText();
        String Alamat = alamat.getText();
        String num = kodeSopir.getText();

        if (nama_supir.isEmpty() || no_ktp.isEmpty() || no_tlp.isEmpty() || Alamat.isEmpty()) {
            pop_upRequired required = new pop_upRequired();
            required.setVisible(true);
            return;
        }
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql;
            if (id != null) {
                sql = "UPDATE supir SET nama_supir = '" + namaSopir.getText() + "', no_ktp = '" + noKtp.getText() + "'"
                        + ",no_telp = '" + noTelp.getText() + "',alamat = '" + alamat.getText() + "' WHERE kd_supir = '" + kodeSopir.getText() + "'";

                statement.executeUpdate(sql);
                pop_upDataberhasil dataubah = new pop_upDataberhasil();
                dataubah.setVisible(true);
                PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Perubahan data Sopir";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                }
            } else {
                ResultSet res = statement.executeQuery("SELECT genSupirID() AS supirID");
                String kdSupir = "";
                if (res.next()) {
                    kdSupir = res.getString("supirID");
                }
                sql = "insert into supir VALUES('" + kdSupir + "','" + nama_supir + "', '" + no_ktp + "',"
                        + " '" + no_tlp + "','" + Alamat + "','bersedia');";

                PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Penambahan data Sopir";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                }
            }
            statement.executeUpdate(sql);
            pop_upDataberhasil dataubah = new pop_upDataberhasil();
            dataubah.setVisible(true);
            statement.close();
            sopir.datatable();

            this.dispose();

        } catch (Exception e) {
            System.out.println(e);
            pop_upDataGagal datagagal = new pop_upDataGagal();
            datagagal.setVisible(true);
        }
    }//GEN-LAST:event_saveSopirMouseClicked

    public void clear() {
        noKtp.setText(null);
        namaSopir.setText(null);
        noTelp.setText(null);
        alamat.setText(null);
    }
    private void jButton_hapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_hapus1MouseClicked
        // TODO add your handling code here:

        try {

            pop_upTanyaClear tanya = new pop_upTanyaClear(this);
            tanya.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_hapus1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formSopirv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formSopirv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formSopirv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formSopirv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formSopirv2(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JLabel jButton_hapus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodeSopir;
    private javax.swing.JTextField namaSopir;
    private javax.swing.JTextField noKtp;
    private javax.swing.JTextField noTelp;
    private javax.swing.JButton saveMobil;
    private javax.swing.JLabel saveSopir;
    // End of variables declaration//GEN-END:variables
}
