/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Penyewaan;

import DB_koneksi.DB;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import rental.Dashboardadmin;

/**
 *
 * @author sakab
 */
public class SewaMasterv2 extends javax.swing.JPanel {

    /**
     * Creates new form SewaMaster
     */
    Dashboardadmin dashboard;

//    public SewaMaster() {
//        initComponents();
//    }
    public SewaMasterv2(Dashboardadmin dashboard) {
        initComponents();
        this.dashboard = dashboard;
        datatable();
    }

    public void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Sewa");
        tbl.addColumn("Nama Customer");
        tbl.addColumn("Nama Mobil");
        tbl.addColumn("Harga Sewa");
        tbl.addColumn("Nama Sopir");
        jTable_master.setModel(tbl);
        jTable_master.getColumnModel().getColumn(0).setMinWidth(0);
        jTable_master.getColumnModel().getColumn(0).setMaxWidth(0);
        
        //filter ASC DESC
//         String filterType = Filter.getSelectedItem().toString();
         
        String cari = jTextField_search.getText();
        ArrayList<String> filter = new ArrayList<>();
        StringBuilder sql = new StringBuilder("SELECT * FROM v_detailsewa");
//        if (!cari.isEmpty()) {
//            filter.add("no_ktp  LIKE '%"+ cari +"%' or nama_lengkap  LIKE '%"+ cari +"%'");
//        }
//        if (!filter.isEmpty()) {
//            sql.append(" WHERE ").append(String.join(" AND ",filter));
//        }
//        if (filterType.equals("A-Z")) {
//            sql.append(" ORDER BY kd_customer ASC;");
//        } else if (filterType.equals("Z-A")) {
//            sql.append(" ORDER BY kd_customer DESC;");
//        }
        String newSql = sql.toString();
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery(newSql);
            System.out.println(res.next());
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kd_penyewaan"),
                    res.getString("nama_customer"),
                    res.getString("nama_mobil"),
                    res.getString("subtotal"),
                    res.getString("nama_supir"),
                    
                });
                jTable_master.setModel(tbl);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ada");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_master = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(977, 528));
        setPreferredSize(new java.awt.Dimension(977, 528));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_search.setBackground(new java.awt.Color(238, 218, 222));
        jTextField_search.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextField_search.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_search.setBorder(null);
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });
        add(jTextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 510, 60));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tambah");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 150, 60));

        jTable_master.setBackground(new java.awt.Color(238, 218, 222));
        jTable_master.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTable_master.setForeground(new java.awt.Color(51, 51, 51));
        jTable_master.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Sewa", "Nama Customer", "Nama Mobil", "Harga Sewa", "Nama Sopir"
            }
        ));
        jTable_master.setRowHeight(40);
        jTable_master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_masterMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_master);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 1280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/konten_masterSewa.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1466, 928));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased

    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jTable_masterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_masterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_masterMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JPanel body = dashboard.getJpanelBody();
        body.removeAll();
        body.add(new Sewav2());
        body.revalidate();
    }//GEN-LAST:event_jLabel2MouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_master;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
