/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Penyewaan;

import DB_koneksi.DB;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import rental.Dashboardadmin;

/**
 *
 * @author sakab
 */
public class SewaMaster extends javax.swing.JPanel {

    /**
     * Creates new form SewaMaster
     */
    Dashboardadmin dashboard;

//    public SewaMaster() {
//        initComponents();
//    }
    public SewaMaster(Dashboardadmin dashboard) {
        initComponents();
        this.dashboard = dashboard;
        datatable();
    }

    public void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Sewa");
        tbl.addColumn("Nama Customer");
        tbl.addColumn("Nama Mobil");
        tbl.addColumn("Harga Sewa");
        tbl.addColumn("Nama Sopir");
        jTable_master.setModel(tbl);
        jTable_master.getColumnModel().getColumn(0).setMinWidth(0);
        jTable_master.getColumnModel().getColumn(0).setMaxWidth(0);
        
        //filter ASC DESC
//         String filterType = Filter.getSelectedItem().toString();
         
        String cari = jTextField_search.getText();
        ArrayList<String> filter = new ArrayList<>();
        StringBuilder sql = new StringBuilder("SELECT * FROM `v_detailsewa`");
//        if (!cari.isEmpty()) {
//            filter.add("no_ktp  LIKE '%"+ cari +"%' or nama_lengkap  LIKE '%"+ cari +"%'");
//        }
//        if (!filter.isEmpty()) {
//            sql.append(" WHERE ").append(String.join(" AND ",filter));
//        }
//        if (filterType.equals("A-Z")) {
//            sql.append(" ORDER BY kd_customer ASC;");
//        } else if (filterType.equals("Z-A")) {
//            sql.append(" ORDER BY kd_customer DESC;");
//        }
        String newSql = sql.toString();
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery(newSql);
            System.out.println(res.next());
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kd_penyewaan"),
                    res.getString("nama_customer"),
                    res.getString("nama_mobil"),
                    res.getString("subtotal"),
                    res.getString("nama_supir"),
                    
                });
                jTable_master.setModel(tbl);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ada");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_master = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton_add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_master = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(977, 528));
        setPreferredSize(new java.awt.Dimension(977, 528));

        jPanel_master.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(177, 16, 7));
        jLabel8.setText("Penyewaan");

        jTextField_search.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Search");

        jButton_add.setBackground(new java.awt.Color(255, 0, 51));
        jButton_add.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jTable_master.setBackground(new java.awt.Color(238, 218, 222));
        jTable_master.setForeground(new java.awt.Color(51, 51, 51));
        jTable_master.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Sewa", "Nama Customer", "Nama Mobil", "Harga Sewa", "Nama Sopir"
            }
        ));
        jTable_master.setRowHeight(40);
        jTable_master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_masterMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_master);

        javax.swing.GroupLayout jPanel_masterLayout = new javax.swing.GroupLayout(jPanel_master);
        jPanel_master.setLayout(jPanel_masterLayout);
        jPanel_masterLayout.setHorizontalGroup(
            jPanel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_masterLayout.createSequentialGroup()
                .addGroup(jPanel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_masterLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_add)
                            .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel_masterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(561, Short.MAX_VALUE))
        );
        jPanel_masterLayout.setVerticalGroup(
            jPanel_masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_masterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(610, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_master, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_master, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_masterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_masterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_masterMouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        JPanel body = dashboard.getJpanelBody();
        body.removeAll();
        body.add(new Sewav2());
        body.revalidate();
    }//GEN-LAST:event_jButton_addActionPerformed
    
    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased

    }//GEN-LAST:event_jTextField_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel_master;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_master;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
