/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package owner;

import History.History;


import Penyewaan.Sewa;

import dataAdmin.Userv2;


import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;


import Laporan.Menu_Laporan;
import Laporan.Menu_Laporanv2;
import Mobil.Mobilv2;
import PemilikMobil.dataPemilikv2;
import Sopir.Sopirv2;
import dataCustomer.Custv2;

import rental.dashboardOwner;
import rental.login;

/**
 *
 * @author sakab
 */
public class dashboardOwnerV1 extends javax.swing.JFrame {

    private JPanel Mobil;
    /**
     * Creates new form Dashboard
     */

    //      border
    Border red_border = BorderFactory.createMatteBorder(0, 0, 4, 0, Color.red);
    Border empty_border = BorderFactory.createMatteBorder(0, 0, 0, 0,Color.white);

    public dashboardOwnerV1() {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);

        //        set border di menu item
        jLabel_dashboard.setBorder(empty_border);
        jLabel_dataMobil.setBorder(empty_border);
        jLabel_dataSopir.setBorder(empty_border);

        //        menu item
//        displayImage(jLabel_icon_dashboard.getWidth(), jLabel_icon_dashboard.getHeight(), "../images/icon_menu/icon_dashboard.png", jLabel_icon_dashboard);
//
//        displayImage(jLabel_icon_data_mobil.getWidth(), jLabel_icon_data_mobil.getHeight(), "../images/icon_menu/mobil.png", jLabel_icon_data_mobil);
//        displayImage(jLabel_icon_data_sopir.getWidth(), jLabel_icon_data_sopir.getHeight(), "../images/icon_menu/sopir.png", jLabel_icon_data_sopir);
//        displayImage(jLabel_icon_data_user.getWidth(), jLabel_icon_data_user.getHeight(), "../images/icon_menu/user.png", jLabel_icon_data_user);
//        displayImage(jLabel_icon_data_cust.getWidth(), jLabel_icon_data_cust.getHeight(), "../images/icon_menu/cust.png", jLabel_icon_data_cust);
//        displayImage(jLabel_icon_data_history.getWidth(), jLabel_icon_data_history.getHeight(), "../images/icon_menu/History.png", jLabel_icon_data_history);
//        displayImage(jLabel_icon_data_pemilik.getWidth(), jLabel_icon_data_pemilik.getHeight(), "../images/icon_menu/user.png", jLabel_icon_data_pemilik);
//        displayImage(jLabel_icon_laporan.getWidth(), jLabel_icon_laporan.getHeight(), "../images/icon_menu/laporan.png", jLabel_icon_laporan);

        Date date = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
        jLabel_tgl.setText(tgl.format(date));
        jPanel_body.removeAll();
        jPanel_body.add(new dashboardOwner());
        jPanel_body.revalidate();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_dataMobil = new javax.swing.JLabel();
        jLabel_dataSopir = new javax.swing.JLabel();
        jLabel_dataAdmin = new javax.swing.JLabel();
        jLabel_dataCustomer = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jLabel_dataPemilik = new javax.swing.JLabel();
        jLabel_Laporan = new javax.swing.JLabel();
        jLabel_dashboard = new javax.swing.JLabel();
        jPanel_body = new javax.swing.JPanel();
        jLabel_History = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jLabel_tgl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_dataMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_dataMobil.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_dataMobil.setText("Data Mobil");
        jLabel_dataMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataMobilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataMobilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataMobilMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_dataMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel_dataSopir.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_dataSopir.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_dataSopir.setText("Data Sopir");
        jLabel_dataSopir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataSopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataSopirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataSopirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataSopirMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_dataSopir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel_dataAdmin.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_dataAdmin.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_dataAdmin.setText("Data User");
        jLabel_dataAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataAdminMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_dataAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, -1, -1));

        jLabel_dataCustomer.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_dataCustomer.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_dataCustomer.setText("Data Customer");
        jLabel_dataCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_dataCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        jLabel_logout.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel_logout.setForeground(new java.awt.Color(153, 0, 0));
        jLabel_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logout.setText("Keluar");
        jLabel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 910, 170, 70));

        jLabel_dataPemilik.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_dataPemilik.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_dataPemilik.setText("Pemilik Mobil");
        jLabel_dataPemilik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataPemilik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataPemilikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataPemilikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataPemilikMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_dataPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, -1, -1));

        jLabel_Laporan.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_Laporan.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Laporan.setText("Laporan");
        jLabel_Laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_LaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_LaporanMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 760, -1, -1));

        jLabel_dashboard.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_dashboard.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_dashboard.setText("Dashboard");
        jLabel_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jPanel_body.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_body.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel_body, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 1460, 930));

        jLabel_History.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_History.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_History.setText(" History");
        jLabel_History.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_History.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_HistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_HistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_HistoryMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_History, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 830, -1, -1));

        exit.setBackground(new java.awt.Color(204, 0, 51));
        exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 0, 20, -1));

        jLabel_tgl.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_tgl.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel_tgl.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_tgl.setText("jLabel1");
        getContentPane().add(jLabel_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 500, -1));

        jPanel1.setBackground(new java.awt.Color(177, 0, 7));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 480, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dashboard Owner.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseClicked
        dashboardOwner dashboard = new dashboardOwner();
        jPanel_body.removeAll();
        jPanel_body.add(dashboard);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dashboardMouseClicked

    private void jLabel_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseEntered
        // TODO add your handling code here:
        jLabel_dashboard.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dashboardMouseEntered

    private void jLabel_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseExited
        // TODO add your handling code here:
        jLabel_dashboard.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dashboardMouseExited

    private void jLabel_dataMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataMobilMouseClicked
        // TODO add your handling code here:
        Mobilv2 mob = new Mobilv2();
        jPanel_body.removeAll();
        jPanel_body.add(mob);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataMobilMouseClicked

    private void jLabel_dataMobilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataMobilMouseEntered
        // TODO add your handling code here:
        jLabel_dataMobil.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataMobilMouseEntered

    private void jLabel_dataMobilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataMobilMouseExited
        // TODO add your handling code here:
        jLabel_dataMobil.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataMobilMouseExited

    private void jLabel_dataSopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataSopirMouseClicked
        // TODO add your handling code here:
        Sopirv2 sopir = new Sopirv2();
        jPanel_body.removeAll();
        jPanel_body.add(sopir);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataSopirMouseClicked

    private void jLabel_dataSopirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataSopirMouseEntered
        // TODO add your handling code here:
        jLabel_dataSopir.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataSopirMouseEntered

    private void jLabel_dataSopirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataSopirMouseExited
        // TODO add your handling code here:
        jLabel_dataSopir.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataSopirMouseExited

    private void jLabel_dataAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataAdminMouseClicked

        Userv2 user = new Userv2();
        jPanel_body.removeAll();
        jPanel_body.add(user);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataAdminMouseClicked

    private void jLabel_dataAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataAdminMouseEntered
        // TODO add your handling code here:
        jLabel_dataAdmin.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataAdminMouseEntered

    private void jLabel_dataAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataAdminMouseExited
        // TODO add your handling code here:
        jLabel_dataAdmin.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataAdminMouseExited

    private void jLabel_dataCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseClicked

        Custv2 cust = new Custv2();
        jPanel_body.removeAll();
        jPanel_body.add(cust);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataCustomerMouseClicked

    private void jLabel_dataCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseEntered
        // TODO add your handling code here:
        jLabel_dataCustomer.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataCustomerMouseEntered

    private void jLabel_dataCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseExited
        // TODO add your handling code here:
        jLabel_dataCustomer.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataCustomerMouseExited

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
       login front = new login();
        this.dispose();
        front.setVisible(true);
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    private void jLabel_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_logoutMouseEntered

    private void jLabel_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel_logoutMouseExited

    private void jLabel_dataPemilikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataPemilikMouseClicked
        // TODO add your handling code here:
        dataPemilikv2 pemilik = new dataPemilikv2();
        jPanel_body.removeAll();
        jPanel_body.add(pemilik);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataPemilikMouseClicked

    private void jLabel_dataPemilikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataPemilikMouseEntered
        // TODO add your handling code here:
        jLabel_dataPemilik.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataPemilikMouseEntered

    private void jLabel_dataPemilikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataPemilikMouseExited
        // TODO add your handling code here:
        jLabel_dataPemilik.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataPemilikMouseExited

    private void jLabel_LaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LaporanMouseClicked
        // TODO add your handling code here:
        
        jPanel_body.removeAll();
        jPanel_body.add(new Menu_Laporanv2(this));
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_LaporanMouseClicked

    private void jLabel_LaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LaporanMouseEntered
        // TODO add your handling code here:
        jLabel_Laporan.setBorder(red_border);
    }//GEN-LAST:event_jLabel_LaporanMouseEntered

    private void jLabel_LaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LaporanMouseExited
        // TODO add your handling code here:
        jLabel_Laporan.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_LaporanMouseExited

    private void jLabel_HistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HistoryMouseClicked
        // TODO add your handling code here:
        History pemilik = new History();
        jPanel_body.removeAll();
        jPanel_body.add(pemilik);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_HistoryMouseClicked

    private void jLabel_HistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HistoryMouseEntered
        // TODO add your handling code here:
        jLabel_History.setBorder(red_border);
    }//GEN-LAST:event_jLabel_HistoryMouseEntered

    private void jLabel_HistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_HistoryMouseExited
        // TODO add your handling code here:
        jLabel_History.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_HistoryMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    public JPanel getJPanelBody() {
        return this.jPanel_body;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardOwnerV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardOwnerV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardOwnerV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardOwnerV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardOwnerV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_History;
    private javax.swing.JLabel jLabel_Laporan;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_dataAdmin;
    private javax.swing.JLabel jLabel_dataCustomer;
    private javax.swing.JLabel jLabel_dataMobil;
    private javax.swing.JLabel jLabel_dataPemilik;
    private javax.swing.JLabel jLabel_dataSopir;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JLabel jLabel_tgl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_body;
    // End of variables declaration//GEN-END:variables
}
