/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package owner;

import History.History;
import Mobil.Mobil;
import Mobil.Mobil;
import PemilikMobil.dataPemilik;
import Penyewaan.Sewa;
import Sopir.Sopir;
import dataAdmin.User;

import dataCustomer.Customer;
import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;
import History.dataLog;
import Laporan.L_pelanggaran;
import Laporan.L_sewa;
import Laporan.Menu_Laporan;
import rental.dashboardAdmin;
import rental.login;

/**
 *
 * @author sakab
 */
public class dashboardOwner extends javax.swing.JFrame {

    private JPanel Mobil;
    /**
     * Creates new form Dashboard
     */

    //      border
    Border red_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.red);
    Border empty_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(254, 254, 254));

    public dashboardOwner() {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);

        //        set border di menu item
        jLabel_dashboard.setBorder(empty_border);

        jLabel_dataMobil.setBorder(empty_border);
        jLabel_dataSopir.setBorder(empty_border);

        //        menu item
        displayImage(jLabel_icon_dashboard.getWidth(), jLabel_icon_dashboard.getHeight(), "../images/icon_menu/icon_dashboard.png", jLabel_icon_dashboard);

        displayImage(jLabel_icon_data_mobil.getWidth(), jLabel_icon_data_mobil.getHeight(), "../images/icon_menu/mobil.png", jLabel_icon_data_mobil);
        displayImage(jLabel_icon_data_sopir.getWidth(), jLabel_icon_data_sopir.getHeight(), "../images/icon_menu/sopir.png", jLabel_icon_data_sopir);
        displayImage(jLabel_icon_data_user.getWidth(), jLabel_icon_data_user.getHeight(), "../images/icon_menu/user.png", jLabel_icon_data_user);
        displayImage(jLabel_icon_data_cust.getWidth(), jLabel_icon_data_cust.getHeight(), "../images/icon_menu/cust.png", jLabel_icon_data_cust);
        displayImage(jLabel_icon_data_history.getWidth(), jLabel_icon_data_history.getHeight(), "../images/icon_menu/History.png", jLabel_icon_data_history);
        displayImage(jLabel_icon_data_pemilik.getWidth(), jLabel_icon_data_pemilik.getHeight(), "../images/icon_menu/user.png", jLabel_icon_data_pemilik);
        displayImage(jLabel_icon_laporan.getWidth(), jLabel_icon_laporan.getHeight(), "../images/icon_menu/laporan.png", jLabel_icon_laporan);

        Date date = new Date();
        SimpleDateFormat tgl = new SimpleDateFormat("yyyy-MM-dd");
        jLabel_tgl.setText(tgl.format(date));
        jPanel_body.removeAll();
        jPanel_body.add(new dashboardAdmin());
        jPanel_body.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_tgl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_hallo_owner = new javax.swing.JLabel();
        owner = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_dataMobil = new javax.swing.JLabel();
        jLabel_dataSopir = new javax.swing.JLabel();
        jLabel_dashboard = new javax.swing.JLabel();
        jLabel_icon_data_mobil = new javax.swing.JLabel();
        jLabel_icon_data_sopir = new javax.swing.JLabel();
        jLabel_icon_dashboard = new javax.swing.JLabel();
        jLabel_Keluar2 = new javax.swing.JLabel();
        jLabel_dataAdmin = new javax.swing.JLabel();
        jLabel_dataCustomer = new javax.swing.JLabel();
        jLabel_icon_data_user = new javax.swing.JLabel();
        jLabel_icon_data_cust = new javax.swing.JLabel();
        jLabel_dataCustomer1 = new javax.swing.JLabel();
        jLabel_icon_data_history = new javax.swing.JLabel();
        jLabel_dataPemilik = new javax.swing.JLabel();
        jLabel_icon_data_pemilik = new javax.swing.JLabel();
        jLabel_Laporan = new javax.swing.JLabel();
        jLabel_icon_laporan = new javax.swing.JLabel();
        jPanel_body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(177, 16, 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 100));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel_tgl.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel_tgl.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_hallo_owner.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel_hallo_owner.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_hallo_owner.setText("Hello,");

        owner.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        owner.setForeground(new java.awt.Color(255, 255, 255));
        owner.setText("Hello,");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(367, 367, 367)
                .addComponent(jLabel_hallo_owner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(owner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addComponent(jLabel_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_hallo_owner)
                                .addComponent(owner))
                            .addComponent(jLabel_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));

        jLabel_dataMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dataMobil.setText("Data Mobil");
        jLabel_dataMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataMobilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataMobilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataMobilMouseExited(evt);
            }
        });

        jLabel_dataSopir.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dataSopir.setText("Data Sopir");
        jLabel_dataSopir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataSopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataSopirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataSopirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataSopirMouseExited(evt);
            }
        });

        jLabel_dashboard.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dashboard.setText("Dashboard");
        jLabel_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseExited(evt);
            }
        });

        jLabel_icon_data_mobil.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_data_mobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_data_mobil.setOpaque(true);

        jLabel_icon_data_sopir.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_data_sopir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_data_sopir.setOpaque(true);

        jLabel_icon_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_dashboard.setOpaque(true);

        jLabel_Keluar2.setBackground(new java.awt.Color(204, 0, 51));
        jLabel_Keluar2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_Keluar2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Keluar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Keluar2.setText("Keluar");
        jLabel_Keluar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Keluar2.setOpaque(true);
        jLabel_Keluar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Keluar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Keluar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Keluar2MouseExited(evt);
            }
        });

        jLabel_dataAdmin.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dataAdmin.setText("Data User");
        jLabel_dataAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataAdminMouseExited(evt);
            }
        });

        jLabel_dataCustomer.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dataCustomer.setText("Data Customer");
        jLabel_dataCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomerMouseExited(evt);
            }
        });

        jLabel_icon_data_user.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_data_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_data_user.setOpaque(true);

        jLabel_icon_data_cust.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_data_cust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_data_cust.setOpaque(true);

        jLabel_dataCustomer1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dataCustomer1.setText(" History");
        jLabel_dataCustomer1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataCustomer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomer1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomer1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataCustomer1MouseExited(evt);
            }
        });

        jLabel_icon_data_history.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_data_history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_data_history.setOpaque(true);

        jLabel_dataPemilik.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_dataPemilik.setText("Owner Mobil");
        jLabel_dataPemilik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dataPemilik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dataPemilikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_dataPemilikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_dataPemilikMouseExited(evt);
            }
        });

        jLabel_icon_data_pemilik.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_data_pemilik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_data_pemilik.setOpaque(true);

        jLabel_Laporan.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel_Laporan.setText("Laporan");
        jLabel_Laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_LaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_LaporanMouseExited(evt);
            }
        });

        jLabel_icon_laporan.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_icon_laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_icon_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_icon_laporan.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_icon_data_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_data_sopir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_data_user, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_data_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_data_history, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_data_pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_dataSopir)
                            .addComponent(jLabel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_dataMobil)
                            .addComponent(jLabel_dataAdmin)
                            .addComponent(jLabel_dataCustomer)
                            .addComponent(jLabel_dataPemilik)
                            .addComponent(jLabel_Laporan)
                            .addComponent(jLabel_dataCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel_Keluar2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_dataMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_icon_data_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel_dataSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_icon_data_sopir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_data_user, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dataCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_data_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dataCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_data_history, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_dataPemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_data_pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_icon_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel_Keluar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel_body.setBackground(new java.awt.Color(243, 245, 250));
        jPanel_body.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel_body.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayImage(int width, int height, String image_path, JLabel label) {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource(image_path));
        Image image = imageIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);

        label.setIcon(new ImageIcon(image));

    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel_dataPemilikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataPemilikMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_dataPemilikMouseExited

    private void jLabel_dataPemilikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataPemilikMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_dataPemilikMouseEntered

    private void jLabel_dataPemilikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataPemilikMouseClicked
        // TODO add your handling code here:
        dataPemilik pemilik = new dataPemilik();
        jPanel_body.removeAll();
        jPanel_body.add(pemilik);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataPemilikMouseClicked

    private void jLabel_dataCustomer1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomer1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_dataCustomer1MouseExited

    private void jLabel_dataCustomer1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomer1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_dataCustomer1MouseEntered

    private void jLabel_dataCustomer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomer1MouseClicked
        dataLog history = new dataLog();
        jPanel_body.removeAll();
        jPanel_body.add(history);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataCustomer1MouseClicked

    private void jLabel_dataCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseExited
        // TODO add your handling code here:
        jLabel_dataCustomer.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataCustomerMouseExited

    private void jLabel_dataCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseEntered
        // TODO add your handling code here:
        jLabel_dataCustomer.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataCustomerMouseEntered

    private void jLabel_dataCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataCustomerMouseClicked

        Customer cust = new Customer();
        jPanel_body.removeAll();
        jPanel_body.add(cust);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataCustomerMouseClicked

    private void jLabel_dataAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataAdminMouseExited
        // TODO add your handling code here:
        jLabel_dataAdmin.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataAdminMouseExited

    private void jLabel_dataAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataAdminMouseEntered
        // TODO add your handling code here:
        jLabel_dataAdmin.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataAdminMouseEntered

    private void jLabel_dataAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataAdminMouseClicked

        User user = new User();
        jPanel_body.removeAll();
        jPanel_body.add(user);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataAdminMouseClicked

    private void jLabel_Keluar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Keluar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Keluar2MouseExited

    private void jLabel_Keluar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Keluar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Keluar2MouseEntered

    private void jLabel_Keluar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Keluar2MouseClicked
        login front = new login();
        this.dispose();
        front.setVisible(true);

    }//GEN-LAST:event_jLabel_Keluar2MouseClicked

    private void jLabel_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseExited
        // TODO add your handling code here:
        jLabel_dashboard.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dashboardMouseExited

    private void jLabel_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseEntered
        // TODO add your handling code here:
        jLabel_dashboard.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dashboardMouseEntered

    private void jLabel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseClicked
        jPanel_body.removeAll();
        jPanel_body.repaint();
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dashboardMouseClicked

    private void jLabel_dataSopirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataSopirMouseExited
        // TODO add your handling code here:
        jLabel_dataSopir.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataSopirMouseExited

    private void jLabel_dataSopirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataSopirMouseEntered
        // TODO add your handling code here:
        jLabel_dataSopir.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataSopirMouseEntered

    private void jLabel_dataSopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataSopirMouseClicked
        // TODO add your handling code here:
        Sopir sopir = new Sopir();
        jPanel_body.removeAll();
        jPanel_body.add(sopir);
        jPanel_body.revalidate();

    }//GEN-LAST:event_jLabel_dataSopirMouseClicked

    private void jLabel_dataMobilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataMobilMouseExited
        // TODO add your handling code here:
        jLabel_dataMobil.setBorder(empty_border);
    }//GEN-LAST:event_jLabel_dataMobilMouseExited

    private void jLabel_dataMobilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataMobilMouseEntered
        // TODO add your handling code here:
        jLabel_dataMobil.setBorder(red_border);
    }//GEN-LAST:event_jLabel_dataMobilMouseEntered

    private void jLabel_dataMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dataMobilMouseClicked
        // TODO add your handling code here:
        Mobil mob = new Mobil();
        jPanel_body.removeAll();
        jPanel_body.add(mob);
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_dataMobilMouseClicked

    private void jLabel_LaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LaporanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_LaporanMouseExited

    private void jLabel_LaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LaporanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_LaporanMouseEntered

    private void jLabel_LaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LaporanMouseClicked
        // TODO add your handling code here:
        jPanel_body.removeAll();
        jPanel_body.add(new Menu_Laporan(this));
        jPanel_body.revalidate();
    }//GEN-LAST:event_jLabel_LaporanMouseClicked

    public JPanel getJPanelBody() {
        return this.jPanel_body;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Keluar2;
    private javax.swing.JLabel jLabel_Laporan;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_dataAdmin;
    private javax.swing.JLabel jLabel_dataCustomer;
    private javax.swing.JLabel jLabel_dataCustomer1;
    private javax.swing.JLabel jLabel_dataMobil;
    private javax.swing.JLabel jLabel_dataPemilik;
    private javax.swing.JLabel jLabel_dataSopir;
    javax.swing.JLabel jLabel_hallo_owner;
    private javax.swing.JLabel jLabel_icon_dashboard;
    private javax.swing.JLabel jLabel_icon_data_cust;
    private javax.swing.JLabel jLabel_icon_data_history;
    private javax.swing.JLabel jLabel_icon_data_mobil;
    private javax.swing.JLabel jLabel_icon_data_pemilik;
    private javax.swing.JLabel jLabel_icon_data_sopir;
    private javax.swing.JLabel jLabel_icon_data_user;
    private javax.swing.JLabel jLabel_icon_laporan;
    private javax.swing.JLabel jLabel_tgl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_body;
    public static javax.swing.JLabel owner;
    // End of variables declaration//GEN-END:variables
}
