/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Laporan;

import PemilikMobil.*;
import Sopir.*;
import ActionButton.TableActionEditor;
import ActionButton.TableActionEvent;
import ActionButton.tabelActionRender;
import DB_koneksi.DB;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakab
 */
public class L_PelanggaranV2 extends javax.swing.JPanel {

    /**
     * Creates new form Sopir
     */
    public L_PelanggaranV2() {
        initComponents();
        datatable("","");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Laporan_pelanggaran = new javax.swing.JTable();
        btn_reset = new javax.swing.JLabel();
        btn_search = new javax.swing.JLabel();
        jTanggal1 = new com.toedter.calendar.JDateChooser();
        jTanggal2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Laporan_pelanggaran.setBackground(new java.awt.Color(238, 218, 222));
        Laporan_pelanggaran.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Laporan_pelanggaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Sopir", "No.Telp", "Alamat", "Status", "KodeSopir", "Action"
            }
        ));
        Laporan_pelanggaran.setRowHeight(40);
        Laporan_pelanggaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Laporan_pelanggaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Laporan_pelanggaran);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 1330, -1));

        btn_reset.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_reset.setText("Reset");
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMouseClicked(evt);
            }
        });
        add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 200, 170, 60));

        btn_search.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_search.setText("Search");
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });
        add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 180, 60));
        add(jTanggal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 340, 50));
        add(jTanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 340, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/L_pelanggaran.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1920, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void Laporan_pelanggaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Laporan_pelanggaranMouseClicked
        // TODO add your handling code here:
        //        int baris = jTableSopir.rowAtPoint(evt.getPoint());
        //        String id_supir = jTableSopir.getValueAt(baris, 0).toString();
        //
        //        formSopir frm_add = new formSopir(id_supir,this);
        //        frm_add.setVisible(true);
    }//GEN-LAST:event_Laporan_pelanggaranMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
        try {
            Laporan_pelanggaran.setModel(new DefaultTableModel(null,new Object[]{"kd_pelanggaran","kd_penyewaan","nama_supir","nama_mobil","ganti_rugi","keterangan","tgl_pelanggaran"}));
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = df.format(jTanggal1.getDate());
            String date2 = df.format(jTanggal2.getDate());
            datatable(date1,date2);

        }
        catch(Exception e) {

        }
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseClicked
        // TODO add your handling code here:
        jTanggal1.setDate(null);
        jTanggal2.setDate(null);
        datatable("","");
    }//GEN-LAST:event_btn_resetMouseClicked

    void datatable(String d1,String d2){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kd Pelanggaran");
        tbl.addColumn("Kd Penyewaan");
        tbl.addColumn("Nama supir");
        tbl.addColumn("Nama mobil");
        tbl.addColumn("Ganti rugi");
        tbl.addColumn("Keterangan");
        tbl.addColumn("Tgl_pelanggaran");
        
        Laporan_pelanggaran.setModel(tbl);
        
         PreparedStatement st;
        ResultSet res;
        try {
            if (d1.equals("") || d2.equals("")) {
                st = DB.getConnection().prepareStatement("SELECT * FROM `v_pelanggaran`");
            }
            else {
                st = DB.getConnection().prepareStatement("SELECT * FROM `v_pelanggaran` where tgl_pelanggaran between ? and ? ");
                st.setString(1, d1);
                st.setString(2, d2);
            }
            
            res = st.executeQuery();
            DefaultTableModel model = (DefaultTableModel) Laporan_pelanggaran.getModel();
            
            Object[] row;
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kd_pelanggaran"),
                    res.getString("kd_penyewaan"),
                    (res.getString("nama_supir") == null) ? "Tidak Ada Supir" : res.getString("nama_supir"),
                    res.getString("nama_mobil"),
                    res.getString("ganti_rugi"),
                    res.getString("keterangan"),
                    //                     res.getString("gambar"),
                    res.getString("tgl_pelanggaran")
                });
                Laporan_pelanggaran.setModel(tbl);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak ada");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Laporan_pelanggaran;
    private javax.swing.JLabel btn_reset;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jTanggal1;
    private com.toedter.calendar.JDateChooser jTanggal2;
    // End of variables declaration//GEN-END:variables
}
