/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Laporan;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import owner.dashboardOwner;
import rental.Dashboard;

/**
 *
 * @author Hidayah-Arif
 */
public class Menu_Laporan extends javax.swing.JPanel {

    dashboardOwner dashboard = new dashboardOwner();

    public Menu_Laporan(dashboardOwner dashboard) {
        initComponents();
        laporan_penyewaan_icon.setSize(450, 242);
        // Code adding the component to the parent container - not shown here
        ImageIcon image1 = new ImageIcon(getClass().getResource("/images/laporan_penyewaan_vector.png"));
        Image im1 = image1.getImage();
        Image myimg = im1.getScaledInstance(laporan_penyewaan_icon.getWidth(), laporan_penyewaan_icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myimg);
        laporan_penyewaan_icon.setIcon(newImage);
        ImageIcon image2 = new ImageIcon(getClass().getResource("/images/laporan_pelanggaran_vector.png"));
        Image im2 = image2.getImage();
        Image myimg2 = im2.getScaledInstance(laporan_penyewaan_icon.getWidth(), laporan_penyewaan_icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImage2 = new ImageIcon(myimg2);
        laporan_pelanggaran_icon.setIcon(newImage2);
//        laporan_penyewaan_icon.setSize(45, 40);
        this.dashboard = dashboard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        laporan_penyewaan_icon = new javax.swing.JLabel();
        laporan_pelanggaran_icon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(177, 16, 7));
        jLabel8.setText("Menu Laporan");

        laporan_penyewaan_icon.setBackground(new java.awt.Color(255, 255, 255));
        laporan_penyewaan_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporan_penyewaan_icon.setOpaque(true);
        laporan_penyewaan_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporan_penyewaan_iconMouseClicked(evt);
            }
        });

        laporan_pelanggaran_icon.setBackground(new java.awt.Color(255, 255, 255));
        laporan_pelanggaran_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporan_pelanggaran_icon.setOpaque(true);
        laporan_pelanggaran_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporan_pelanggaran_iconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(laporan_penyewaan_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(laporan_pelanggaran_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laporan_penyewaan_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporan_pelanggaran_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void laporan_penyewaan_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_penyewaan_iconMouseClicked
        dashboard.getJPanelBody().removeAll();
        dashboard.getJPanelBody().add(new L_sewa());
        dashboard.getJPanelBody().revalidate();
    }//GEN-LAST:event_laporan_penyewaan_iconMouseClicked

    private void laporan_pelanggaran_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_pelanggaran_iconMouseClicked
        dashboard.getJPanelBody().removeAll();
        dashboard.getJPanelBody().add(new L_pelanggaran());
        dashboard.getJPanelBody().revalidate();
    }//GEN-LAST:event_laporan_pelanggaran_iconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel laporan_pelanggaran_icon;
    private javax.swing.JLabel laporan_penyewaan_icon;
    // End of variables declaration//GEN-END:variables
}
