/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Laporan;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

import owner.dashboardOwnerV1;

/**
 *
 * @author Hidayah-Arif
 */
public class Menu_Laporanv2 extends javax.swing.JPanel {

    dashboardOwnerV1 dashboard = new dashboardOwnerV1();

  
    public Menu_Laporanv2(dashboardOwnerV1 dashboard) {
        initComponents();
//        laporan_penyewaan_icon.setSize(45, 40);
        this.dashboard = dashboard;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laporan_sewa = new javax.swing.JLabel();
        laporan_pengembalian = new javax.swing.JLabel();
        laporan_pembatalan = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laporan_sewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporan_sewaMouseClicked(evt);
            }
        });
        add(laporan_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 410, 300));

        laporan_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporan_pengembalianMouseClicked(evt);
            }
        });
        add(laporan_pengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, 410, 300));

        laporan_pembatalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporan_pembatalanMouseClicked(evt);
            }
        });
        add(laporan_pembatalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 410, 300));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_laporan.png"))); // NOI18N
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgMouseClicked(evt);
            }
        });
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1472, 936));
    }// </editor-fold>//GEN-END:initComponents

    private void laporan_sewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_sewaMouseClicked
        // TODO add your handling code here:
        dashboard.getJPanelBody().removeAll();
        dashboard.getJPanelBody().add(new L_Sewav2());
        dashboard.getJPanelBody().revalidate();
    }//GEN-LAST:event_laporan_sewaMouseClicked

    private void bgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseClicked

    }//GEN-LAST:event_bgMouseClicked

    private void laporan_pembatalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_pembatalanMouseClicked
        // TODO add your handling code here:
        dashboard.getJPanelBody().removeAll();
        dashboard.getJPanelBody().add(new L_PembatalanV2() );
        dashboard.getJPanelBody().revalidate();
    }//GEN-LAST:event_laporan_pembatalanMouseClicked

    private void laporan_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_pengembalianMouseClicked
        // TODO add your handling code here:
        dashboard.getJPanelBody().removeAll();
        dashboard.getJPanelBody().add(new L_PengembalianV2());
        dashboard.getJPanelBody().revalidate();
    }//GEN-LAST:event_laporan_pengembalianMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel laporan_pembatalan;
    private javax.swing.JLabel laporan_pengembalian;
    private javax.swing.JLabel laporan_sewa;
    // End of variables declaration//GEN-END:variables
}
