/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PemilikMobil;

import Sopir.*;
import ActionButton.TableActionEditor;
import ActionButton.TableActionEvent;
import ActionButton.tabelActionRender;
import DB_koneksi.DB;
import functions.pop_upBerhasilHapus;
import functions.pop_upHapus;
import functions.pop_updataTerhubung;
import functions.pop_upnoData;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakab
 */
public class dataPemilikv2 extends javax.swing.JPanel {

    /**
     * Creates new form Sopir
     */
    public dataPemilikv2() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tambah = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePemilik = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Filter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_tambah.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tambah.setText("Tambah");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 240, 70));

        jTextField_search.setBackground(new java.awt.Color(238, 218, 222));
        jTextField_search.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jTextField_search.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_search.setBorder(null);
        jTextField_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchActionPerformed(evt);
            }
        });
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });
        add(jTextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 510, 60));

        jTablePemilik.setBackground(new java.awt.Color(238, 218, 222));
        jTablePemilik.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTablePemilik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Sopir", "No.Telp", "Alamat", "Status", "KodeSopir", "Action"
            }
        ));
        jTablePemilik.setRowHeight(60);
        jTablePemilik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePemilikMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePemilik);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 1330, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(177, 0, 7));
        jLabel1.setText("Data Pemilik Mobil");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        Filter.setBackground(new java.awt.Color(238, 218, 222));
        Filter.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        Filter.setForeground(new java.awt.Color(255, 51, 51));
        Filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sortir", "Terbaru", "Terlama" }));
        Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterActionPerformed(evt);
            }
        });
        add(Filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 210, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/masterSupir.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1920, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        formPemilikv2 frm_sopir = new formPemilikv2(null, this);
        frm_sopir.setVisible(true);
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void jTextField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchActionPerformed

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jTablePemilikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePemilikMouseClicked
        // TODO add your handling code here:
        //        int baris = jTableSopir.rowAtPoint(evt.getPoint());
        //        String id_supir = jTableSopir.getValueAt(baris, 0).toString();
        //
        //        formSopir frm_add = new formSopir(id_supir,this);
        //        frm_add.setVisible(true);
    }//GEN-LAST:event_jTablePemilikMouseClicked

    private void FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_FilterActionPerformed

    public void datatable() {
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                int baris = row;
                String id_pemilik = jTablePemilik.getValueAt(baris, 0).toString();
                formPemilikv2 frm_add = new formPemilikv2(id_pemilik, getThis());
                frm_add.setVisible(true);
            }

            private dataPemilikv2 getThis() { // create a method to return the outer class instance
                return dataPemilikv2.this;
            }

            @Override
            public void onDelete(int row) {
                int baris = row;
                String id_pemilik = jTablePemilik.getValueAt(baris, 0).toString();
                try {
//                 pop_upHapus hapus = new pop_upHapus();
//                 hapus.setVisible(true);
//                    if (JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus ?", "Pesan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
//                        PreparedStatement pst = DB.getConnection().prepareStatement("delete from pemilik_mobil where kd_pemilik = ?");
//                        pst.setString(1, id_pemilik);
//                        pst.executeUpdate();
//                        pop_upBerhasilHapus berhasil = new pop_upBerhasilHapus();
//                        berhasil.setVisible(true);
//                         PreparedStatement ps;
//                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
//                ResultSet result = ps.executeQuery();
//                while (result.next()) {
//                    String activity = "Melakukan Penghapusan data Pemilik Mobil";
//                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
//                    ps.executeUpdate();
//                    break;
//                }
//                        new dataPemilikv2().datatable();
//                        datatable();
//                }
                    String activity = "Melakukan Penghapusan data Pemilik Mobil";
                    pop_upHapus pop = new pop_upHapus("delete from pemilik_mobil where kd_pemilik = '" + id_pemilik + "'", activity, getThis(), "datatable");
                    pop.setVisible(true);

                } catch (Exception e) {
                    pop_updataTerhubung hubung = new pop_updataTerhubung();
                    hubung.setVisible(true);
                }
            }

        };

        DefaultTableModel tbl = new DefaultTableModel();

        tbl.addColumn(
                "Kode Pemilik");
        tbl.addColumn(
                "Nama Pemilik");
        tbl.addColumn(
                "No Ktp");
        tbl.addColumn(
                "Alamat");
        tbl.addColumn(
                "No Telp");
        tbl.addColumn(
                "Action");
        jTablePemilik.setModel(tbl);

        //filter ASC DESC
        String filterType = Filter.getSelectedItem().toString();

        String cari = jTextField_search.getText();
        ArrayList<String> filter = new ArrayList<>();
        StringBuilder sql = new StringBuilder("SELECT * from pemilik_mobil");

        if (!cari.isEmpty()) {
            filter.add("nama_pemilik LIKE '%" + cari + "%' or kd_pemilik LIKE '%" + cari + "%' or no_ktp LIKE '%" + cari + "%'");
            
        }

        if (!filter.isEmpty()) {
            sql.append(" WHERE ").append(String.join(" AND ", filter));
        }

        if (filterType.equals(
                "Terlama")) {
            sql.append(" ORDER BY kd_pemilik ASC;");
        } else if (filterType.equals(
                "Terbaru")) {
            sql.append(" ORDER BY kd_pemilik DESC;");
        }
        String newSql = sql.toString();

        System.out.println(newSql);

        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery(newSql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kd_pemilik"),
                    res.getString("nama_pemilik"),
                    res.getString("no_ktp"),
                    res.getString("alamat"),
                    res.getString("no_telp"),});
                jTablePemilik.setModel(tbl);
                jTablePemilik.getColumnModel().getColumn(5).setCellRenderer(new tabelActionRender());
                jTablePemilik.getColumnModel().getColumn(5).setCellEditor(new TableActionEditor(event));
            }
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Filter;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePemilik;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
