/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PemilikMobil;

import dataCustomer.*;
import DB_koneksi.DB;
import alert.alert_hapus;
import functions.pop_upClear;
import functions.pop_upDataGagal;
import functions.pop_upDataberhasil;
import functions.pop_upRequired;
import functions.pop_upTanyaClear;
import functions.pop_upnoData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sakab
 */
public class formPemilikv2 extends javax.swing.JFrame {

    String id;
    dataPemilikv2 DataPemilik;

    /**
     * Creates new form Form_Mobil
     */
    public formPemilikv2(String id_pemilik, dataPemilikv2 DataPemilik) {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);

//        Image();
        initComponents();
//        this.id_pemilik = id_pemilik;
        jScrollPane1.setBorder(null);
        this.setLocationRelativeTo(null);
        id = id_pemilik;
        this.DataPemilik = DataPemilik;

        if (id_pemilik != null) {
            getData(id_pemilik);
            kodePemilik.setText(id_pemilik);
        }

        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveMobil = new javax.swing.JButton();
        jButton_hapus = new javax.swing.JButton();
        kodePemilik = new javax.swing.JTextField();
        noKtp = new javax.swing.JTextField();
        noTelp = new javax.swing.JTextField();
        namaPemilik = new javax.swing.JTextField();
        saveSopir = new javax.swing.JLabel();
        jButton_hapus1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        saveMobil.setBackground(new java.awt.Color(255, 0, 51));
        saveMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saveMobil.setForeground(new java.awt.Color(255, 255, 255));
        saveMobil.setText("Save");
        saveMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMobilActionPerformed(evt);
            }
        });

        jButton_hapus.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kodePemilik.setBackground(new java.awt.Color(238, 218, 222));
        kodePemilik.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        kodePemilik.setEnabled(false);
        kodePemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodePemilikActionPerformed(evt);
            }
        });
        getContentPane().add(kodePemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 400, 40));

        noKtp.setBackground(new java.awt.Color(238, 218, 222));
        noKtp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        noKtp.setForeground(new java.awt.Color(0, 0, 0));
        noKtp.setBorder(null);
        noKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noKtpActionPerformed(evt);
            }
        });
        getContentPane().add(noKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 320, 30));

        noTelp.setBackground(new java.awt.Color(238, 218, 222));
        noTelp.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        noTelp.setBorder(null);
        noTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpActionPerformed(evt);
            }
        });
        getContentPane().add(noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 320, 40));

        namaPemilik.setBackground(new java.awt.Color(238, 218, 222));
        namaPemilik.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        namaPemilik.setForeground(new java.awt.Color(0, 0, 0));
        namaPemilik.setBorder(null);
        namaPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPemilikActionPerformed(evt);
            }
        });
        getContentPane().add(namaPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 330, 40));

        saveSopir.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        saveSopir.setForeground(new java.awt.Color(255, 255, 255));
        saveSopir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveSopir.setText("Simpan");
        saveSopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveSopirMouseClicked(evt);
            }
        });
        getContentPane().add(saveSopir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 120, 50));

        jButton_hapus1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton_hapus1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_hapus1.setText("Reset");
        jButton_hapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_hapus1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 110, 50));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        alamat.setBackground(new java.awt.Color(238, 218, 222));
        alamat.setColumns(20);
        alamat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        alamat.setForeground(new java.awt.Color(0, 0, 0));
        alamat.setRows(5);
        alamat.setBorder(null);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 530, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modal_pemilik.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -1, 1040, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getData(String id_pemilik) {
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM pemilik_mobil where kd_pemilik ='" + id_pemilik + "'");

            while (res.next()) {
                namaPemilik.setText(res.getString("nama_pemilik"));
                noKtp.setText(res.getString("no_ktp"));
                noTelp.setText(res.getString("no_telp"));
                alamat.setText(res.getString("alamat"));
                //                   status.setText(res.getString("nopol"));
            }
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);

        }
    }
    private void saveMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMobilActionPerformed

    }//GEN-LAST:event_saveMobilActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton_hapusActionPerformed

    private void kodePemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodePemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodePemilikActionPerformed

    private void noKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noKtpActionPerformed

    private void noTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpActionPerformed

    private void namaPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemilikActionPerformed

    private void saveSopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveSopirMouseClicked
        // TODO add your handling code here:
        String nama_pemilik = namaPemilik.getText();
        String noktp = noKtp.getText();
        String no_tlp = noTelp.getText();
        String Alamat = alamat.getText();
        String num = kodePemilik.getText();

        if (nama_pemilik.isEmpty() || noktp.isEmpty() || no_tlp.isEmpty() || Alamat.isEmpty()) {
            pop_upRequired required = new pop_upRequired();
            required.setVisible(true);
            return;

        }
//        String id_pemilik = this.id_pemilik;

        //        String status = statusMobil.getText();
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql;
            if (id != null) {
                sql = "UPDATE `pemilik_mobil` SET `nama_pemilik`='" + nama_pemilik + "',`alamat`='" + Alamat + "',`no_telp`='" + no_tlp + "',`no_ktp`='" + noktp + "' WHERE kd_pemilik = '" + kodePemilik.getText() + "'";
                statement.executeUpdate(sql);
                pop_upDataberhasil dataubah = new pop_upDataberhasil();
                dataubah.setVisible(true);
                PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Perubahan data Pemilik Mobil";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                }
            } else {
                ResultSet res = statement.executeQuery("SELECT genPemilikID() AS pemilikID");
                String kdPemilik = "";
                if (res.next()) {
                    kdPemilik = res.getString("pemilikID");
                }
                sql = "insert into pemilik_mobil VALUES('" + kdPemilik + "','" + nama_pemilik + "', '" + Alamat + "', '" + no_tlp + "','" + noktp + "');";

                PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Penambahan data Pemilik Mobil";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                }
            }
            statement.executeUpdate(sql);
            pop_upDataberhasil dataubah = new pop_upDataberhasil();
            dataubah.setVisible(true);
            statement.close();
            System.out.println(sql);
            DataPemilik.datatable();

            this.dispose();
        } catch (Exception e) {
            System.out.println(e);
            pop_upDataGagal datagagal = new pop_upDataGagal();
            datagagal.setVisible(true);
        }
    }//GEN-LAST:event_saveSopirMouseClicked
    public void clear() {
        namaPemilik.setText(null);
        noKtp.setText(null);
        noTelp.setText(null);
        alamat.setText(null);
    }
    private void jButton_hapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_hapus1MouseClicked
        // TODO add your handling code here:
        try {
            // pop_upTanyaClear tanya = new pop_upTanyaClear();
//             tanya.setVisible(true);
//            if (JOptionPane.showConfirmDialog(null, "Yakin ingin mengkosongkan seluruh data ?", "Pesan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
//                namaPemilik.setText(null);
//                noKtp.setText(null);
//                noTelp.setText(null);
//                alamat.setText(null);
//                pop_upClear clear = new pop_upClear();
//                clear.setVisible(true);
//            }
            pop_upTanyaClear clear = new pop_upTanyaClear(this);
            clear.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_hapus1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPemilikv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPemilikv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPemilikv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPemilikv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPemilikv2(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JLabel jButton_hapus1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodePemilik;
    private javax.swing.JTextField namaPemilik;
    private javax.swing.JTextField noKtp;
    private javax.swing.JTextField noTelp;
    private javax.swing.JButton saveMobil;
    private javax.swing.JLabel saveSopir;
    // End of variables declaration//GEN-END:variables
}
