/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PemilikMobil;

import Mobil.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import DB_koneksi.DB;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import DB_koneksi.DB;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.io.FileInputStream;
import java.nio.file.Files;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sakab
 */
public class Form_Pemilik extends javax.swing.JFrame {

    String id;
    dataPemilik DataPemilik;

    /**
     * Creates new form Form_Mobil
     */
    public Form_Pemilik(String id_pemilik, dataPemilik DataPemilik) {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);

//        Image();
        initComponents();
        this.setLocationRelativeTo(null);
        id = id_pemilik;
        this.DataPemilik = DataPemilik;
        
        
        if (id_pemilik != null) {
            getData(id_pemilik);
            kodePemilik.setText(id_pemilik);
        }

        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
    }

  
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kodePemilik = new javax.swing.JTextField();
        noKtp = new javax.swing.JTextField();
        noTelp = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        saveMobil = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_file = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        namaPemilik = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kodePemilik.setBackground(new java.awt.Color(238, 218, 222));
        kodePemilik.setEnabled(false);
        kodePemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodePemilikActionPerformed(evt);
            }
        });
        jPanel1.add(kodePemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 400, 30));

        noKtp.setBackground(new java.awt.Color(238, 218, 222));
        noKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noKtpActionPerformed(evt);
            }
        });
        jPanel1.add(noKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 400, 30));

        noTelp.setBackground(new java.awt.Color(238, 218, 222));
        noTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTelpActionPerformed(evt);
            }
        });
        jPanel1.add(noTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 400, 30));

        alamat.setBackground(new java.awt.Color(238, 218, 222));
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 400, 70));

        saveMobil.setBackground(new java.awt.Color(255, 0, 51));
        saveMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saveMobil.setForeground(new java.awt.Color(255, 255, 255));
        saveMobil.setText("Save");
        saveMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMobilMouseClicked(evt);
            }
        });
        saveMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMobilActionPerformed(evt);
            }
        });
        jPanel1.add(saveMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 120, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Form Pemilik");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("KTP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Alamat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("No Telp");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Nama Pemilik");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel_file.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_file.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_file.setText("##");
        jPanel1.add(jLabel_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, 20));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Kode Pemilik");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton_hapus.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 120, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        namaPemilik.setBackground(new java.awt.Color(238, 218, 222));
        namaPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPemilikActionPerformed(evt);
            }
        });
        jPanel1.add(namaPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 400, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void getData(String id_pemilik) {
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM pemilik_mobil where kd_pemilik ='"+id_pemilik+"'");

            while (res.next()) {
                namaPemilik.setText(res.getString("nama_pemilik"));
                noKtp.setText(res.getString("no_ktp"));
                noTelp.setText(res.getString("no_telp"));
                alamat.setText(res.getString("alamat"));
                //                   status.setText(res.getString("nopol"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }
//   
    
    private void noKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noKtpActionPerformed

    private void noTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTelpActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void saveMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMobilActionPerformed
        // TODO add your handling code here:

        String nama_pemilik = namaPemilik.getText();
        String noktp = noKtp.getText();
        String no_tlp = noTelp.getText();
        String Alamat = alamat.getText();
        String num = kodePemilik.getText();

        //        String status = statusMobil.getText();
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql;
            if (id != null) {   
                sql = "UPDATE `pemilik_mobil` SET `nama_pemilik`='"+nama_pemilik+"',`alamat`='"+Alamat+"',`no_telp`='"+no_tlp+"',`no_ktp`='"+noktp+"' WHERE kd_pemilik = '"+kodePemilik.getText()+"'";
                JOptionPane.showMessageDialog(null,"Data berhasil di Ubah");
            } else {
                ResultSet res = statement.executeQuery("SELECT genPemilikID() AS pemilikID");
                String kdPemilik = ""; 
                if(res.next()){
                    kdPemilik = res.getString("pemilikID");
                }
                sql = "insert into pemilik_mobil VALUES('" + kdPemilik + "','" + nama_pemilik + "', '" + Alamat + "', '" + no_tlp + "','" + noktp + "');";
                JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            }
            statement.executeUpdate(sql);
            statement.close();
            System.out.println(sql);
            DataPemilik.datatable();
            
            this.dispose();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "data gagal di SIMPAN");
        }
    }//GEN-LAST:event_saveMobilActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:
        try {
            if (id != null) {
                Statement statement = (Statement) DB.getConnection().createStatement();
                String sql;
                if (JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus ?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                    sql = "DELETE FROM pemilik_mobil where kd_pemilik = '" + kodePemilik.getText() + "'";
                    java.sql.Connection conn = (Connection) DB.getConnection();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    DataPemilik.datatable();
                    this.dispose();

                }

            } else {
                namaPemilik.setText(null);
                noKtp.setText(null);
                noTelp.setText(null);
                alamat.setText(null);
                JOptionPane.showMessageDialog(this, "Data berhasil dikosongkan");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_hapusActionPerformed

    private void saveMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMobilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMobilMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void namaPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemilikActionPerformed

    private void kodePemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodePemilikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodePemilikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Pemilik(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_file;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kodePemilik;
    private javax.swing.JTextField namaPemilik;
    private javax.swing.JTextField noKtp;
    private javax.swing.JTextField noTelp;
    private javax.swing.JButton saveMobil;
    // End of variables declaration//GEN-END:variables
}
