/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Mobil;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import DB_koneksi.DB;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import DB_koneksi.DB;
import com.mysql.cj.jdbc.PreparedStatementWrapper;
import java.io.FileInputStream;
import java.nio.file.Files;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sakab
 */
public class Form_Mobil extends javax.swing.JFrame {

    ArrayList<String> nm_pemilik, kd_pemilik;
    String id;
    String imagePath;
    String imagePathOld;
    Mobilv2 mobil;
    Boolean isBrowsePressed = false;

    /**
     * Creates new form Form_Mobil
     */
    public Form_Mobil(String id_mobil, Mobilv2 mobil) {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);

//        Image();
        initComponents();
//        this.setLocationRelativeTo(null);
        getPemilik();
//        tampilGambar(jLabel_foto,id_mobil);
        id = id_mobil;
        this.mobil = mobil;
        if (id_mobil != null) {
            getData(id_mobil);
            kodeMobil.setText(id_mobil);
        }

        //ini agar posisi center waktu buka
        this.setLocationRelativeTo(null);
    }

    void getData(String id_mobil) {
        PreparedStatement ts = null;
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT pemilik_mobil.nama_pemilik,mobil.* FROM mobil inner join pemilik_mobil ON pemilik_mobil.kd_pemilik = mobil.kd_pemilik where kd_mobil ='" + id_mobil + "'");

            while (res.next()) {

                namaMobil.setText(res.getString("nama_mobil"));
                nopolMobil.setText(res.getString("nopol"));
                
                
                tahun.setText(res.getString("tahun_produksi"));
                harga.setText(res.getString("harga_perhari"));
                String img_path = res.getString("gambar");
                this.imagePathOld = img_path;
                ImageIcon image = new ImageIcon(img_path);
                Image im = image.getImage();
                Image myimg = im.getScaledInstance(jLabel_foto.getWidth(), jLabel_foto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myimg);
                jLabel_foto.setIcon(newImage);
                System.out.println(newImage);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }

    void getPemilik() {
        nm_pemilik = new ArrayList<String>();
        kd_pemilik = new ArrayList<String>();
        try {
            Statement state = DB.getConnection().createStatement();
            ResultSet res = state.executeQuery("select kd_pemilik, nama_pemilik from pemilik_mobil");
            while (res.next()) {
                jComboBox_pemilik.addItem(res.getString("nama_pemilik"));
                kd_pemilik.add(res.getString("kd_pemilik"));
            }

        } catch (Exception x) {
            JOptionPane.showMessageDialog(rootPane, x);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kodeMobil = new javax.swing.JTextField();
        nopolMobil = new javax.swing.JTextField();
        jComboBox_pemilik = new javax.swing.JComboBox<>();
        tahun = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        saveMobil = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_browse = new javax.swing.JButton();
        jLabel_foto = new javax.swing.JLabel();
        jLabel_file = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        namaMobil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kodeMobil.setBackground(new java.awt.Color(238, 218, 222));
        kodeMobil.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        kodeMobil.setEnabled(false);
        kodeMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeMobilActionPerformed(evt);
            }
        });
        jPanel1.add(kodeMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 320, 60));

        nopolMobil.setBackground(new java.awt.Color(238, 218, 222));
        nopolMobil.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        nopolMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopolMobilActionPerformed(evt);
            }
        });
        jPanel1.add(nopolMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 320, 60));

        jComboBox_pemilik.setBackground(new java.awt.Color(238, 218, 222));
        jComboBox_pemilik.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(jComboBox_pemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 320, 60));

        tahun.setBackground(new java.awt.Color(238, 218, 222));
        tahun.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunActionPerformed(evt);
            }
        });
        jPanel1.add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 320, 60));

        harga.setBackground(new java.awt.Color(238, 218, 222));
        harga.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel1.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 320, 60));

        saveMobil.setBackground(new java.awt.Color(255, 0, 51));
        saveMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        saveMobil.setForeground(new java.awt.Color(255, 255, 255));
        saveMobil.setText("Save");
        saveMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMobilMouseClicked(evt);
            }
        });
        saveMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMobilActionPerformed(evt);
            }
        });
        jPanel1.add(saveMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 720, 137, 70));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Form Mobil");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("No Polisi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 190, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setText("Harga Perhari");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 230, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("Tahun Produksi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 240, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setText("Foto Mobil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setText("Nama Mobil");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setText("Nama Pemilik");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        jButton_browse.setBackground(new java.awt.Color(255, 0, 0));
        jButton_browse.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jButton_browse.setForeground(new java.awt.Color(255, 255, 255));
        jButton_browse.setText("Browse");
        jButton_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_browseActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 137, 70));

        jLabel_foto.setBackground(new java.awt.Color(238, 218, 222));
        jLabel_foto.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel_foto.setOpaque(true);
        jPanel1.add(jLabel_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 310, 250));

        jLabel_file.setBackground(new java.awt.Color(255, 239, 246));
        jLabel_file.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_file.setText("##");
        jPanel1.add(jLabel_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, 20));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel7.setText("Kode Mobil");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 210, -1));

        jButton_hapus.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jButton_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus.setText("Clear");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 720, 137, 70));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, 20, 20));

        namaMobil.setBackground(new java.awt.Color(238, 218, 222));
        namaMobil.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        namaMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaMobilActionPerformed(evt);
            }
        });
        jPanel1.add(namaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 320, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 831));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    public void tampilGambar(JLabel jLabel_foto,String id_mobil){
//        try{
//            String sql = "SELECT gambar where kd_mobil ='" + id_mobil + "'";
//            Statement stn = DB.getConnection().createStatement();
//            ResultSet rs = stn.executeQuery(sql);
//            
//            if (rs.next()) {
//                byte[] img = rs.getBytes("gambar");
//                if (img != null) {
//                    ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(jLabel_foto.getWidth(), jLabel_foto.getHeight(), Image.SCALE_SMOOTH));
//                    jLabel_foto.setIcon(imageIcon);
//                }
//                else {
//                    ImageIcon defaultIcon = new ImageIcon(getClass().getResource("../images/icon_menu/mobil.png"));
//                    jLabel_foto.setIcon(defaultIcon);
//                }
//            }
//        } catch(Exception e){
//            
//        }
//    }

    public ImageIcon resizeImage(String imagePath) {
        ImageIcon imgIcon = new ImageIcon(imagePath);
        Image img = imgIcon.getImage();
        Image newImg = img.getScaledInstance(jLabel_foto.getWidth(), jLabel_foto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public String getImagePath() {

        return imagePath;

    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    private void nopolMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopolMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopolMobilActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void saveMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMobilActionPerformed
        String nama_mobil = namaMobil.getText();
        String nopol = nopolMobil.getText();
        String pemilik = kd_pemilik.get(jComboBox_pemilik.getSelectedIndex());
        String tahun_produksi = tahun.getText();
        String harga_perhari = harga.getText();
        String imagePath = jLabel_file.getText();
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql = "";
            if (id != null) {
                System.out.println("Apakah tombol ditekan");
                System.out.println(this.isBrowsePressed);
                if (!this.isBrowsePressed) {
                    System.out.println("Tidak tertekan");
                    sql = "UPDATE mobil SET nama_mobil = '" + nama_mobil + "', nopol = '" + nopol + "',tahun_produksi = '" + tahun_produksi + "',kd_pemilik = '" + pemilik + "',harga_perhari = '" + harga_perhari + "' WHERE mobil.kd_mobil = '" + kodeMobil.getText() + "'";
                    JOptionPane.showMessageDialog(null, "data berhasil di Ubah");
                } else {

                    JFileChooser f = new JFileChooser();
                    f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                    f.showSaveDialog(null);
                    String new_path = f.getSelectedFile().toString();
                    File oldFile = new File(imagePathOld);
                    File newFile = new File(imagePath);
                    File newFileDir = null;
                    String ext = imagePath.substring(imagePath.lastIndexOf('.') + 1);
                    newFileDir = new File(new_path + "/" + nama_mobil + "." + ext);
                    Files.delete(oldFile.toPath());
                    Files.copy(newFile.toPath(), newFileDir.toPath());
                    String pathToInsert = newFileDir.toString().replace("\\", "/");
                    sql = "UPDATE mobil SET nama_mobil = '" + nama_mobil + "', nopol = '" + nopol + "',tahun_produksi = '" + tahun_produksi + "',kd_pemilik = '" + pemilik + "',harga_perhari = '" + harga_perhari + "',gambar = '" + pathToInsert + "' WHERE mobil.kd_mobil = '" + kodeMobil.getText() + "'";
                    JOptionPane.showMessageDialog(null, "data berhasil di Ubah");
                }
            } else {

                JFileChooser f = new JFileChooser();
                f.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
                f.showOpenDialog(null);
                String new_path = f.getSelectedFile().toString();
                File directory = new File(new_path);
                if (!directory.exists()) {
                    directory.mkdirs();
                }
                File fileawal;
                File fileakhir;
                String ext = imagePath.substring(imagePath.lastIndexOf('.') + 1);
                fileawal = new File(imagePath);
                fileakhir = new File(new_path + "/" + nama_mobil + "." + ext);
                String pathToInsert = fileakhir.toString().replace("\\", "/");
                Files.copy(fileawal.toPath(), fileakhir.toPath());
                ResultSet res = statement.executeQuery("SELECT `genMobilID`() AS `mobilID`; ");
                String kdMobil = "";
                if(res.next()){
                    kdMobil = res.getString("mobilID");
                }
                sql = "insert into mobil VALUES('" + kdMobil + "','" + nama_mobil + "', '" + nopol + "', '" + pemilik + "','" + tahun_produksi + "','" + harga_perhari + "', '" + pathToInsert + "', 'tersedia');";
                System.out.println(sql);
                JOptionPane.showMessageDialog(null, "data berhasil di SIMPAN");
            }
            statement.executeUpdate(sql);
            statement.close();
            mobil.datatable();
            

            this.dispose();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "data gagal di SIMPAN");
        }
    }//GEN-LAST:event_saveMobilActionPerformed

    private void jButton_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_browseActionPerformed
        // TODO add your handling code here:
        System.out.println("Pressed Browse");
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png", "jpeg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            jLabel_file.setText(path);
            jLabel_foto.setIcon(resizeImage(path));

            try {
                //                konversi blob gmbr ke imageicon
                byte[] img = Files.readAllBytes(selectedFile.toPath());
                ImageIcon imageIcon = new ImageIcon(img);

                // Set Ukuran gambar
                int labelWidth = 200;
                int labelHeigth = 400;

                // Size gmbr asli
                int imageWidth = imageIcon.getIconWidth();
                int imageHeigth = imageIcon.getIconHeight();

                // hitung skala untk size gmbr yg baru
                double scaleX = (double) labelWidth / (double) imageWidth;
                double scaleY = (double) labelHeigth / (double) imageHeigth;
                double scale = Math.min(scaleX, scaleY);

                //Ubah size gmbr dng skala yg sudah dihitung
                Image scaledImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidth), (int) (scale * imageHeigth), Image.SCALE_SMOOTH);

                //Tampilkan imageIcon ke Jlabel_foto
                jLabel_foto.setIcon(new ImageIcon(scaledImage));
                isBrowsePressed = true;
            } catch (Exception e) {

            }

        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File");
        }

    }//GEN-LAST:event_jButton_browseActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:
        try {
//            if (id != null) {
//                Statement statement = (Statement) DB.getConnection().createStatement();
//                String sql;
//                if (JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus ?", "Pesan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
//
//                    File imgToDel = new File(this.imagePathOld);
//                    System.out.println(this.imagePathOld);
//                    Files.delete(imgToDel.toPath());
//                    sql = "DELETE FROM mobil where kd_mobil = '" + kodeMobil.getText() + "'";
//                    java.sql.Connection conn = (Connection) DB.getConnection();
//                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
//                    pst.execute();
//                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
//                    mobil.datatable();
//                    this.dispose(); 
//
//                }

//            } else {
                if (JOptionPane.showConfirmDialog(null, "Yakin ingin mengkosongkan seluruh data ?", "Pesan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                namaMobil.setText(null);
                nopolMobil.setText(null);
                jComboBox_pemilik.setSelectedItem(this);
                tahun.setText(null);
                harga.setText(null);
                JOptionPane.showMessageDialog(this, "Data berhasil dikosongkan");
                }

            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_hapusActionPerformed

    private void saveMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMobilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMobilMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void namaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaMobilActionPerformed

    private void kodeMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeMobilActionPerformed

    private void tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Mobil(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton_browse;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JComboBox<String> jComboBox_pemilik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_file;
    private javax.swing.JLabel jLabel_foto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kodeMobil;
    private javax.swing.JTextField namaMobil;
    private javax.swing.JTextField nopolMobil;
    private javax.swing.JButton saveMobil;
    private javax.swing.JTextField tahun;
    // End of variables declaration//GEN-END:variables
}
