/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Mobil;

import ActionButton.PanelAction;
import ActionButton.TableActionEditor;
import ActionButton.TableActionEvent;
import ActionButton.tabelActionRender;
import DB_koneksi.DB;
import functions.pop_upBerhasilHapus;
import functions.pop_upHapus;
import functions.pop_updataTerhubung;
import functions.pop_upnoData;
import java.awt.Color;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sakab
 */
public class Mobilv2 extends javax.swing.JPanel {

    /**
     * Creates new form mob
     */
    public Mobilv2() {
        initComponents();
        //jTableMobil.getColumnModel().getColumn(8).setCellRenderer(new tabelActionRender());
        datatable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMobil = new javax.swing.JTable();
        Filter = new javax.swing.JComboBox<>();
        jComboBox_filterStatus = new javax.swing.JComboBox<>();
        btn_tambah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(1472, 936));
        setPreferredSize(new java.awt.Dimension(0, 534));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_search.setBackground(new java.awt.Color(238, 218, 222));
        jTextField_search.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jTextField_search.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_search.setBorder(null);
        jTextField_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchActionPerformed(evt);
            }
        });
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });
        add(jTextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 510, 50));

        jTableMobil.setBackground(new java.awt.Color(238, 218, 222));
        jTableMobil.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTableMobil.setForeground(new java.awt.Color(51, 51, 51));
        jTableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMobil.setGridColor(new java.awt.Color(204, 0, 0));
        jTableMobil.setRowHeight(60);
        jTableMobil.setUpdateSelectionOnSort(false);
        jTableMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMobil);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 1350, 380));

        Filter.setBackground(new java.awt.Color(238, 218, 222));
        Filter.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        Filter.setForeground(new java.awt.Color(255, 51, 51));
        Filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sortir", "Terbaru", "Terlama" }));
        Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterActionPerformed(evt);
            }
        });
        add(Filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 210, 200, 70));

        jComboBox_filterStatus.setBackground(new java.awt.Color(238, 218, 222));
        jComboBox_filterStatus.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        jComboBox_filterStatus.setForeground(new java.awt.Color(255, 0, 51));
        jComboBox_filterStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Tersedia", "Disewa" }));
        jComboBox_filterStatus.setToolTipText("");
        jComboBox_filterStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_filterStatusActionPerformed(evt);
            }
        });
        add(jComboBox_filterStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 210, 220, 70));

        btn_tambah.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tambah.setText("Tambah");
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 220, 80));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(177, 0, 7));
        jLabel1.setText("Data Mobil");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mobilMaster.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1472, 936));
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMobilMouseClicked
        // TODO add your handling code here:
        //        int baris = jTableMobil.rowAtPoint(evt.getPoint());
        //        String id_mobil = jTableMobil.getValueAt(baris, 0).toString();
        //        Form_Mobil frm_add = new Form_Mobil(id_mobil,this);
        //        frm_add.setVisible(true);
    }//GEN-LAST:event_jTableMobilMouseClicked

    private void FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_FilterActionPerformed

    private void jComboBox_filterStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_filterStatusActionPerformed
        datatable();
    }//GEN-LAST:event_jComboBox_filterStatusActionPerformed

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        Form_Mobilv2 frm_addDataMobil = new Form_Mobilv2(null, this);
        frm_addDataMobil.setVisible(true);
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jTextField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchActionPerformed

    public void datatable() {
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                int baris = row;
                String id_mobil = jTableMobil.getValueAt(baris, 0).toString();
                Form_Mobilv2 frm_add = new Form_Mobilv2(id_mobil, getThis());
                frm_add.setVisible(true);
            }

            private Mobilv2 getThis() { // create a method to return the outer class instance
                return Mobilv2.this;
            }

            @Override
            public void onDelete(int row) {
                int baris = row;
                String id_mobil = jTableMobil.getValueAt(baris, 0).toString();
                try {
                    String q1 = "delete from mobil where kd_mobil = '" + id_mobil+"'";
                    String activity = "Melakukan penghapusan data mobil";
                    pop_upHapus pop = new pop_upHapus(q1, activity, getThis(), "datatable");
                    pop.setVisible(true);

                } catch (Exception e) {
                    pop_updataTerhubung hubung = new pop_updataTerhubung();
                    hubung.setVisible(true);
                }
            }

        };
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Mobil");
        tbl.addColumn("Kode Mobil");
        tbl.addColumn("Nama Mobil");
        tbl.addColumn("Nopol");
        tbl.addColumn("Pemilik");
        tbl.addColumn("Tahun Mobil");
        tbl.addColumn("Harga");
        tbl.addColumn("Status");
        tbl.addColumn("Action");
        jTableMobil.setModel(tbl);
        jTableMobil.getColumnModel().getColumn(0).setMinWidth(0);
        jTableMobil.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableMobil.getColumnModel().getColumn(8).setCellRenderer(new tabelActionRender());
        jTableMobil.getColumnModel().getColumn(8).setCellEditor(new TableActionEditor(event));
        String filterType = Filter.getSelectedItem().toString();
        String cari = jTextField_search.getText();
        String filterStatus = jComboBox_filterStatus.getSelectedItem().toString();
        ArrayList<String> filter = new ArrayList<>();
        StringBuilder sql = new StringBuilder("SELECT pemilik_mobil.nama_pemilik,mobil.* FROM mobil "
                + "inner join pemilik_mobil ON pemilik_mobil.kd_pemilik = mobil.kd_pemilik");
        if (!cari.isEmpty()) {
            filter.add("mobil.nama_mobil LIKE '%" + cari + "%' or mobil.nopol LIKE '%" + cari + "%' or mobil.kd_mobil LIKE '%" + cari + "%'");
        }
         if (!filterStatus.isEmpty() && filterStatus != "Semua") {
            filter.add("status = '" + filterStatus + "'");
        }
        if (!filter.isEmpty()) {
            sql.append(" WHERE ").append(String.join(" AND ", filter));
        }
        if (filterType.equals("Terlama")) {
            sql.append(" ORDER BY kd_mobil ASC;");
        } else if (filterType.equals("Terbaru")) {
            sql.append(" ORDER BY kd_mobil DESC;");
        }
        if (!filter.isEmpty()) {
            // add additional filtering conditions to the sql query
        }
        String newSql = sql.toString();
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery(newSql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kd_mobil"),
                    res.getString("kd_mobil"),
                    res.getString("nama_mobil"),
                    res.getString("nopol"),
                    res.getString("nama_pemilik"),
                    res.getString("tahun_produksi"),
                    res.getString("harga_perhari"),
                    res.getString("status")
                });
                jTableMobil.setModel(tbl);
            }
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Filter;
    private javax.swing.JLabel btn_tambah;
    private javax.swing.JComboBox<String> jComboBox_filterStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMobil;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
