/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pembatalan;

import DB_koneksi.DB;
import functions.pop_upnoData;

import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rental.Dashboardadmin;

/**
 *
 * @author sakab
 */
public class Form_Pembatalanv2 extends javax.swing.JFrame {

    Dashboardadmin dashboard;
    String kode_detail_sewa = "";
    String kd_penyewaan = " ";
    Pembatalanv2 v;
//String kd_supir = "";
//   String kd_mobil= "";

    public Form_Pembatalanv2(Pembatalanv2 v) {
        this.dashboard = dashboard;
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
        this.kd_penyewaan = jTextField_search.getText();
        getDetailSewa(jTextField_search.getText());
        this.setLocationRelativeTo(null);
        this.v = v;
    }

    public void getDetailSewa(String kd_penyewaan) {
        DefaultTableModel tbl = new DefaultTableModel();

        tbl.addColumn("kd Detail");
        tbl.addColumn("Nama Mobil");
        tbl.addColumn("Nama Sopir");
        tbl.addColumn("Tgl Sewa");
        tbl.addColumn("Jml Hari");
        tbl.addColumn("Total Harga");

        jTable_detail.setModel(tbl);

        String cari = jTextField_search.getText();
        StringBuilder sql = new StringBuilder("SELECT * FROM v_detailsewa ");
        String newSql = sql.toString().concat(" WHERE status = 'diproses' AND v_detailsewa.kd_penyewaan LIKE '%" + cari + "%' ");
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery(newSql);
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kd_detail_sewa"),
                    res.getString("nama_mobil"),
                    res.getString("nama_supir"),
                    res.getString("tgl_sewa"),
                    res.getString("jml_hari"),
                    res.getString("subtotal")
                });
            }
            jTable_detail.setModel(tbl);
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_sumbit = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_detail = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_sumbit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel_sumbit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sumbit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_sumbit.setText("Submit");
        jLabel_sumbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_sumbitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_sumbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 566, 100, 40));

        jTextField_search.setBackground(new java.awt.Color(255, 217, 217));
        jTextField_search.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jTextField_search.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_search.setBorder(null);
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 210, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(177, 0, 7));
        jLabel6.setText("Kode Transaksi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 310, 40));

        jTable_detail.setBackground(new java.awt.Color(238, 218, 222));
        jTable_detail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTable_detail.setForeground(new java.awt.Color(51, 51, 51));
        jTable_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Detail", "Nama Mobil", "Tgl. Sewa", "Tgl. Tenggat", "Sub Total"
            }
        ));
        jTable_detail.setRowHeight(40);
        jTable_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_detailMouseClicked(evt);
            }
        });
        jTable_detail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_detailKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_detail);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 880, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 4));
        jLabel1.setPreferredSize(new java.awt.Dimension(1027, 659));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_sumbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_sumbitMouseClicked
        // TODO add your handling code here:
//        String kd_detail_sewa = kode_detail_sewa;
//     
//       
//                         
//        try {
//            Statement Statement = DB.getConnection().createStatement();
//            ResultSet res = Statement.executeQuery("SELECT genPembatalanID() AS pembatalanID");
//            String kd_pembatalan = "";
//            if (res.next()) {
//                kd_pembatalan = res.getString("pembatalanID");
//            }
//
//            Statement statement = (Statement) DB.getConnection().createStatement();
//            String sql, sql1;
//            LocalDate tgl_pembatalan = LocalDate.now();
//             int opsi = JOptionPane.showConfirmDialog(null, "Apakah Ada Kerusakan / Pelanggaran ?", "Peringatan", JOptionPane.YES_NO_OPTION);
//                if (opsi == JOptionPane.YES_OPTION) {
//                  Form_denda Form_denda = new Form_denda(kode_detail_sewa, kd_pembatalan, this);
//                    Form_denda.setVisible(true);
//                  
//                } else if (opsi == JOptionPane.NO_OPTION) {
//            sql = "insert into pembatalan VALUES('" + kd_pembatalan + "','" + kd_detail_sewa + "'"
//                    + ",'" + tgl_pembatalan + "' , 0);";
//            sql1 = "update detail_sewa set status = 'selesai' where kd_detail_sewa = '"+kd_detail_sewa+"'";
//            statement.execute(sql);
//            statement.executeUpdate(sql1);           
//            this.dispose();
//                }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
        String kd_penyewaan = this.kd_penyewaan;
        try {
            Statement Statement = DB.getConnection().createStatement();
            ResultSet res = Statement.executeQuery("SELECT genPembatalanID() AS pembatalanID");
            String kd_pembatalan = "";
            if (res.next()) {
                kd_pembatalan = res.getString("pembatalanID");
            }
            Form_denda form = new Form_denda(kode_detail_sewa, kd_pembatalan, kd_penyewaan, this.v);
            form.setVisible(true);
            this.dispose();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jLabel_sumbitMouseClicked

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        // TODO add your handling code here:
        getDetailSewa(jTextField_search.getText());
    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable_detailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_detailMouseClicked
        int baris = jTable_detail.rowAtPoint(evt.getPoint());
        String kd_detail_sewa = jTable_detail.getValueAt(baris, 0).toString();
//        String kd_penyewaan= (String) (jTextField_search.getText());
        kode_detail_sewa = kd_detail_sewa;


    }//GEN-LAST:event_jTable_detailMouseClicked

    private void jTable_detailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_detailKeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_detailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Pembatalanv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Pembatalanv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Pembatalanv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Pembatalanv2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_Pembatalan(null, null).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form_Pembatalan(null, null).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_sumbit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_detail;
    private javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables

}
