/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pembatalan;

import Pembatalan.Form_Pembatalanv2;
import java.awt.*;
import java.awt.event.WindowEvent;
import DB_koneksi.DB;
import DB_koneksi.DB;
import Pembatalan.Form_Pembatalanv2;
import functions.pop_upDataberhasil;
import functions.pop_upnoData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sakab
 */
public class Form_denda extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    String kode_detail_sewa, kd_pembatalan, kd_penyewaan;
    Pembatalanv2 v;

    public Form_denda(String kode_detail_sewa, String kd_pembatalan, String kd_penyewaan, Pembatalanv2 v) {
        initComponents();
        this.kode_detail_sewa = kode_detail_sewa;
        this.kd_pembatalan = kd_pembatalan;
        this.kd_penyewaan = kd_penyewaan;

        getData(kode_detail_sewa);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        setVisible(false);
        getData(kode_detail_sewa);

//        initComponents();
        this.v = v;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jml_hari = new javax.swing.JTextField();
        tgl_tenggat = new javax.swing.JTextField();
        bSave = new javax.swing.JLabel();
        btn_save = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JLabel();
        kode_detail = new javax.swing.JTextField();
        nama_mobil = new javax.swing.JTextField();
        tgl_sewa = new javax.swing.JTextField();
        denda = new javax.swing.JTextField();
        nama_supir = new javax.swing.JTextField();
        harga_perhari = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(1027, 659));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jml_hari.setBackground(new java.awt.Color(238, 218, 222));
        jml_hari.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jml_hari.setBorder(null);
        jml_hari.setEnabled(false);
        jml_hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jml_hariActionPerformed(evt);
            }
        });
        getContentPane().add(jml_hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 230, 40));

        tgl_tenggat.setBackground(new java.awt.Color(238, 218, 222));
        tgl_tenggat.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tgl_tenggat.setEnabled(false);
        tgl_tenggat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_tenggatActionPerformed(evt);
            }
        });
        getContentPane().add(tgl_tenggat, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 230, 40));

        bSave.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        bSave.setForeground(new java.awt.Color(255, 255, 255));
        bSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bSave.setText("Save");
        bSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSaveMouseClicked(evt);
            }
        });
        getContentPane().add(bSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 110, 50));

        btn_save.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_save.setText("Save");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 120, 50));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, -1));

        btnSave.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 120, 50));

        kode_detail.setBackground(new java.awt.Color(238, 218, 222));
        kode_detail.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        kode_detail.setEnabled(false);
        getContentPane().add(kode_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 270, 40));

        nama_mobil.setBackground(new java.awt.Color(238, 218, 222));
        nama_mobil.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nama_mobil.setEnabled(false);
        getContentPane().add(nama_mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 270, 40));

        tgl_sewa.setBackground(new java.awt.Color(238, 218, 222));
        tgl_sewa.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tgl_sewa.setEnabled(false);
        tgl_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_sewaActionPerformed(evt);
            }
        });
        getContentPane().add(tgl_sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 270, 40));

        denda.setBackground(new java.awt.Color(238, 218, 222));
        denda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        denda.setForeground(new java.awt.Color(0, 0, 0));
        denda.setBorder(null);
        denda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dendaActionPerformed(evt);
            }
        });
        getContentPane().add(denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 190, 30));

        nama_supir.setBackground(new java.awt.Color(238, 218, 222));
        nama_supir.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nama_supir.setEnabled(false);
        nama_supir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_supirActionPerformed(evt);
            }
        });
        getContentPane().add(nama_supir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 230, 40));

        harga_perhari.setBackground(new java.awt.Color(238, 218, 222));
        harga_perhari.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        harga_perhari.setEnabled(false);
        harga_perhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_perhariActionPerformed(evt);
            }
        });
        getContentPane().add(harga_perhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 230, 40));

        subtotal.setBackground(new java.awt.Color(238, 218, 222));
        subtotal.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        subtotal.setEnabled(false);
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });
        getContentPane().add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/form denda pembatalan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 660));
    }// </editor-fold>//GEN-END:initComponents
 void getData(String kd_detail_sewa) {
        try {

            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM v_detailsewa  where kd_detail_sewa ='" + kd_detail_sewa + "'");

            while (res.next()) {

                kode_detail.setText(res.getString("kd_detail_sewa"));
                nama_mobil.setText(res.getString("nama_mobil"));
                tgl_sewa.setText(res.getString("tgl_sewa"));
                if (res.getString("nama_supir") != null && !res.getString("nama_supir").isEmpty()) {
                    nama_supir.setText(res.getString("nama_supir"));
                } else {
                    nama_supir.setText("Tidak Ada Sopir");
                }
                harga_perhari.setText(res.getString("harga_perhari"));
                jml_hari.setText(res.getString("jml_hari"));
                subtotal.setText(res.getString("subtotal"));
                tgl_tenggat.setText(res.getString("tgl_tenggat"));
//                     res.getString("gambar"),
//                    status.setText(res.getString("nopol"));
            }
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }


    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked

    }//GEN-LAST:event_btn_saveMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_btnSaveMouseClicked

    private void bSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSaveMouseClicked
        String kode_detail = this.kode_detail_sewa;
        String kode_batal = this.kd_pembatalan;
        String denda_pembatalan = denda.getText();
        String kode_sewa = this.kd_penyewaan;
//       String dp = uang_dp.getText();
//       int uangDp = Integer.parseInt(dp);
//       int denda = Integer.parseInt(denda_pembatalan);
//       int hasil = uangDp-denda;
//       String hasilBatal = String.valueOf(hasil);

        try {
//            System.out.println(kode_detail);
            Statement Statement = DB.getConnection().createStatement();
            String sql, sql1, sql2;
            LocalDate tgl_pembatalan = LocalDate.now();

            sql = "insert into pembatalan VALUES('" + kode_batal + "','" + kode_detail + "'"
                    + ",'" + tgl_pembatalan + "' , '" + denda_pembatalan + "');";
            Statement.executeUpdate(sql);
            pop_upDataberhasil dataubah = new pop_upDataberhasil();
            dataubah.setVisible(true);
            sql1 = "update detail_sewa set status = 'selesai' where kd_detail_sewa = '" + kode_detail + "'";
            Statement.executeUpdate(sql1);
            pop_upDataberhasil dataudbah = new pop_upDataberhasil();
            dataudbah.setVisible(true);
            this.v.generateTableMaster();
//            sql2 = "update penyewaan set bayar = '"+hasilBatal+"' where kd_penyewaan = '"+kode_sewa+"'";
//            Statement.executeUpdate(sql2);
            this.dispose();
            PreparedStatement ps;
            ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
            ResultSet result = ps.executeQuery();
            while (result.next()) {
                String activity = "Melakukan Pembatalan Transaksi";
                ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                ps.executeUpdate();
                break;
            }

        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }

    }//GEN-LAST:event_bSaveMouseClicked

    private void tgl_tenggatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_tenggatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_tenggatActionPerformed

    private void tgl_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_sewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_sewaActionPerformed

    private void nama_supirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_supirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_supirActionPerformed

    private void dendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dendaActionPerformed

    private void jml_hariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jml_hariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jml_hariActionPerformed

    private void harga_perhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_perhariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_perhariActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Denda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Denda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Denda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Denda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_denda(null, null, null, null).setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bSave;
    private javax.swing.JLabel btnSave;
    private javax.swing.JLabel btn_save;
    private javax.swing.JTextField denda;
    private javax.swing.JTextField harga_perhari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jml_hari;
    private javax.swing.JTextField kode_detail;
    private javax.swing.JTextField nama_mobil;
    private javax.swing.JTextField nama_supir;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tgl_sewa;
    private javax.swing.JTextField tgl_tenggat;
    // End of variables declaration//GEN-END:variables

}
