/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package actionbutton_pelunasan;

import ActionButton.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author sakab
 */
public class PanelActionPelunasan extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelActionPelunasan() {
        initComponents();
    }
    
    public void initEvent(TableActionEventPelunasan event,int row){
        btn_pelunasan.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae){
                event.onPelunasan(row);
            }
        });
        
//        hapus.addActionListener(new ActionListener(){
//            @Override
//            public void actionPerformed(ActionEvent ae){
//                event.onView(row);
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action1 = new ActionButton.action();
        action2 = new ActionButton.action();
        action3 = new ActionButton.action();
        btn_pelunasan = new ActionButton.action();

        btn_pelunasan.setBackground(new java.awt.Color(255, 204, 204));
        btn_pelunasan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/actionbutton_pelunasan/btn_pelunasan.png"))); // NOI18N
        btn_pelunasan.setPreferredSize(new java.awt.Dimension(111, 33));
        btn_pelunasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pelunasanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btn_pelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(btn_pelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pelunasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pelunasanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pelunasanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ActionButton.action action1;
    private ActionButton.action action2;
    private ActionButton.action action3;
    private ActionButton.action btn_pelunasan;
    // End of variables declaration//GEN-END:variables
}
