/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package functions;

import DB_koneksi.DB;
import Pengembalian.Pengembalianv2;
import Pengembalian.form_dendaPengembalian;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JFrame;

/**
 *
 * @author sakab
 */
public class pop_upTanyaPengembalian extends javax.swing.JFrame {

    /**
     * Creates new form pop_up_rfidv2
     */
    String kode_detail_sewa;
    String kd_pengembalian;
    Pengembalianv2 v;

    public pop_upTanyaPengembalian(String kode_detail_sewa, String kd_pengembalian, Pengembalianv2 v) {
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.kode_detail_sewa = kode_detail_sewa;
        this.kd_pengembalian = kd_pengembalian;
        this.v = v;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        iya = new javax.swing.JLabel();
        tidak = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 30, 30));

        iya.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        iya.setForeground(new java.awt.Color(255, 255, 255));
        iya.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iya.setText("Iya");
        iya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iyaMouseClicked(evt);
            }
        });
        getContentPane().add(iya, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, 60));

        tidak.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        tidak.setForeground(new java.awt.Color(255, 255, 255));
        tidak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tidak.setText("Tidak");
        tidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tidakMouseClicked(evt);
            }
        });
        getContentPane().add(tidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 110, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pop_upTanyaRusakTidak.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 541, 239));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void iyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iyaMouseClicked
        form_dendaPengembalian frm_denda = new form_dendaPengembalian(kode_detail_sewa, kd_pengembalian, v);
        frm_denda.setVisible(true);
        this.dispose();
// TODO add your handling code here:
        //                namaMobil.setText(null);
        //                nopolMobil.setText(null);
        //                jComboBox_pemilik.setSelectedItem(this);
        //                tahun.setText(null);
        //                harga.setText(null);
        //                pop_upClear clear = new pop_upClear();
        //                clear.setVisible(true);
    }//GEN-LAST:event_iyaMouseClicked

    private void tidakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidakMouseClicked
        try {
            Statement Statement = DB.getConnection().createStatement();
            ResultSet res = Statement.executeQuery("SELECT genPengembalianID() AS pengembalianID");
            String kd_pengembalian = "";
            if (res.next()) {
                kd_pengembalian = res.getString("pengembalianID");
            }

            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql, sql1;
            LocalDate tgl_pengembalian = LocalDate.now();
            pop_upTanyaPengembalian tanya = new pop_upTanyaPengembalian(kode_detail_sewa, kd_pengembalian, v);
            tanya.setVisible(true);
//            int opsi = JOptionPane.showConfirmDialog(null, "Apakah Ada Kerusakan / Pelanggaran ?", "Peringatan", JOptionPane.YES_NO_OPTION);
//            if (opsi == JOptionPane.YES_OPTION) {
//                form_dendaPengembalian frm_denda = new form_dendaPengembalian(kode_detail_sewa, kd_pengembalian, v);
//                frm_denda.setVisible(true);
//                this.dispose();
//            } else if (opsi == JOptionPane.NO_OPTION) {
            sql = "insert into pengembalian VALUES('" + kd_pengembalian + "','" + kode_detail_sewa + "'"
                    + ",'" + tgl_pengembalian + "' , 0, 0);";
            sql1 = "update detail_sewa set status = 'selesai' where kd_detail_sewa = '" + kode_detail_sewa + "'";
            statement.execute(sql);
            statement.executeUpdate(sql1);
            PreparedStatement ps;
            ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
            ResultSet result = ps.executeQuery();
            while (result.next()) {
                String activity = "Melakukan Pengembalian Transaksi";
                ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                ps.executeUpdate();
                break;
            }
//            }
            pop_upDataberhasil dataudbah = new pop_upDataberhasil();
            dataudbah.setVisible(true);
            tanya.setVisible(false);
            this.v.generateTablePengembalianMaster();
            this.dispose();

        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }//GEN-LAST:event_tidakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pop_upTanyaPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pop_upTanyaPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pop_upTanyaPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pop_upTanyaPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pop_upTanyaPengembalian(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel tidak;
    // End of variables declaration//GEN-END:variables
}
