/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dataAdmin;

import javax.swing.*;
import DB_koneksi.DB;
import dataCustomer.formCustomerv2;
import functions.pop_upClear;
import functions.pop_upDataGagal;
import functions.pop_upDataberhasil;
import functions.pop_upRequired;
import functions.pop_upTanyaClear;
import functions.pop_upnoData;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import owner.dashboardOwnerV1;
import rental.Dashboardadmin;
import static rental.login.idUser;
import static rental.login.namaUser;

/**
 *
 * @author sakab
 */
public class formUserv2 extends javax.swing.JFrame {
    
    String id;
    Userv2 user;
    String RFID;
    
    public formUserv2(String id_user, Userv2 user) {
        
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setUndecorated(true);
        initComponents();
        jScrollPane1.setBorder(null);
        this.setLocationRelativeTo(null);
        id = id_user;
        this.user = user;
        buttonGroup1.setSelected(jadmin.getModel(), true);
        
        if (id_user != null) {
            
            getData(id_user);
            kodeUser.setText(id_user);
        }
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveMobil = new javax.swing.JButton();
        jButton_hapus = new javax.swing.JButton();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        namaLengkap = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jCheckBox_showpassword = new javax.swing.JCheckBox();
        save = new javax.swing.JLabel();
        jButton_hapus1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noHp = new javax.swing.JTextField();
        jadmin = new javax.swing.JRadioButton();
        jowner = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        kodeUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rfid = new javax.swing.JTextField();

        saveMobil.setBackground(new java.awt.Color(255, 0, 51));
        saveMobil.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        saveMobil.setForeground(new java.awt.Color(255, 255, 255));
        saveMobil.setText("Save");
        saveMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMobilActionPerformed(evt);
            }
        });

        jButton_hapus.setBackground(new java.awt.Color(255, 0, 51));
        jButton_hapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton_hapus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaLengkap.setBackground(new java.awt.Color(238, 218, 222));
        namaLengkap.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        namaLengkap.setBorder(null);
        namaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapActionPerformed(evt);
            }
        });
        getContentPane().add(namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 420, 40));

        username.setBackground(new java.awt.Color(238, 218, 222));
        username.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 420, 30));

        jPasswordField.setBackground(new java.awt.Color(238, 218, 222));
        jPasswordField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPasswordField.setBorder(null);
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 420, 40));

        jCheckBox_showpassword.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jCheckBox_showpassword.setText("Show Passsword");
        jCheckBox_showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_showpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_showpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        save.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save.setText("Simpan");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 120, 60));

        jButton_hapus1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButton_hapus1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hapus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_hapus1.setText("Reset");
        jButton_hapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_hapus1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton_hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 110, 60));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        noHp.setBackground(new java.awt.Color(238, 218, 222));
        noHp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        noHp.setBorder(null);
        noHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHpActionPerformed(evt);
            }
        });
        getContentPane().add(noHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 420, 30));

        buttonGroup1.add(jadmin);
        jadmin.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jadmin.setForeground(new java.awt.Color(177, 0, 7));
        jadmin.setText("Admin");
        getContentPane().add(jadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, -1, -1));

        buttonGroup1.add(jowner);
        jowner.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jowner.setForeground(new java.awt.Color(177, 0, 7));
        jowner.setText("Owner");
        jowner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jownerActionPerformed(evt);
            }
        });
        getContentPane().add(jowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        Alamat.setBackground(new java.awt.Color(238, 218, 222));
        Alamat.setColumns(20);
        Alamat.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Alamat.setRows(5);
        Alamat.setAutoscrolls(false);
        Alamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 218, 222)));
        Alamat.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(Alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 430, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(177, 0, 7));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SCAN RFID");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 440, 450, 50));

        kodeUser.setBackground(new java.awt.Color(238, 218, 222));
        kodeUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        kodeUser.setEnabled(false);
        kodeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeUserActionPerformed(evt);
            }
        });
        getContentPane().add(kodeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 460, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modal_admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1040, 670));

        rfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfidActionPerformed(evt);
            }
        });
        rfid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rfidKeyReleased(evt);
            }
        });
        getContentPane().add(rfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getData(String id_user) {
        
        try {
            
            Statement statement = (Statement) DB.getConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM user where kd_user ='" + id_user + "'");
            String role = "";
            while (res.next()) {
                namaLengkap.setText(res.getString("nama_lengkap"));
                username.setText(res.getString("username"));
                jPasswordField.setText(res.getString("password"));
                Alamat.setText(res.getString("alamat"));
                noHp.setText(res.getString("hp"));
                role = res.getString("role");
                RFID = res.getString("rfid");
            }
            System.out.println(role);
            if (role.equals("Admin")) {
                jadmin.getModel().setSelected(true);
            } else {
                jowner.getModel().setSelected(true);
            }
        } catch (Exception e) {
            pop_upnoData nodata = new pop_upnoData();
            nodata.setVisible(true);
        }
    }
    private void saveMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMobilActionPerformed

    }//GEN-LAST:event_saveMobilActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton_hapusActionPerformed

    private void namaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaLengkapActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jCheckBox_showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_showpasswordActionPerformed
        // TODO add your handling code here:
        // untuk melihat password
        if (jCheckBox_showpassword.isSelected()) {
            jPasswordField.setEchoChar((char) 0);
        } else {
            jPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox_showpasswordActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        // TODO add your handling code here:
        String nama_lengkap = namaLengkap.getText();
        String User = username.getText();
        String Pass = jPasswordField.getText();
        String alamat = Alamat.getText();
        String hp = noHp.getText();
        String role = null;
        if (jowner.isSelected()) {
            role = "Owner";
        }
        if (jadmin.isSelected()) {
            role = "Admin";
        }
        if (role != null && role.length() > 10) {
            role = role.substring(0, 10);
        }

        // Validation for required data
        if (nama_lengkap.isEmpty() || User.isEmpty() || Pass.isEmpty() || alamat.isEmpty() || hp.isEmpty() || role == null) {
            pop_upRequired required = new pop_upRequired();
            required.setVisible(true);
            return;
        }
//        byte[] RF = RFID.getBytes();
        String num = kodeUser.getText();
        
        try {
            Statement statement = (Statement) DB.getConnection().createStatement();
            String sql;
            if (id != null) {
                sql = "UPDATE `user` SET `nama_lengkap`='" + nama_lengkap + "',`username`='" + User + "',`password`='" + Pass + "',`role`='" + role + "',`alamat`='" + alamat + "',`hp`='" + hp + "',`rfid`='" + RFID + "' WHERE kd_user='" + kodeUser.getText() + "'";
                statement.executeUpdate(sql);
                pop_upDataberhasil dataubah = new pop_upDataberhasil();
                dataubah.setVisible(true);
                PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Perubahan data User";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                }
            } else {
                ResultSet res = statement.executeQuery("SELECT genUserID() AS userID");
                String kdUser = "";
                if (res.next()) {
                    kdUser = res.getString("userID");
                }
                sql = "INSERT INTO user VALUES ('" + kdUser + "','" + nama_lengkap + "','" + RFID + "','" + User + "','" + Pass + "','" + role + "','" + alamat + "','" + hp + "');";
                PreparedStatement ps;
                ps = DB.getConnection().prepareStatement("SELECT * FROM log ORDER BY tgl_log DESC");
                ResultSet result = ps.executeQuery();
                while (result.next()) {
                    String activity = "Melakukan Penambahan data User";
                    ps = DB.getConnection().prepareStatement("CALL createLog('" + result.getString("kd_user") + "','" + activity + "');");
                    ps.executeUpdate();
                    break;
                }
            }
            statement.executeUpdate(sql);
            pop_upDataberhasil dataubah = new pop_upDataberhasil();
            dataubah.setVisible(true);
            statement.close();
            user.datatable();
            
            this.dispose();
            
        } catch (Exception e) {
            System.out.println(e);
            pop_upDataGagal datagagal = new pop_upDataGagal();
            datagagal.setVisible(true);
        }
    }//GEN-LAST:event_saveMouseClicked
    public void clear() {
        namaLengkap.setText(null);
        username.setText(null);
        jPasswordField.setText(null);
        Alamat.setText(null);
        noHp.setText(null);
        rfid.setText(null);
    }
    private void jButton_hapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_hapus1MouseClicked
        // TODO add your handling code here:
        try {
            // pop_upTanyaClear tanya = new pop_upTanyaClear();
//             tanya.setVisible(true);
//            if (JOptionPane.showConfirmDialog(null, "Yakin ingin mengkosongkan seluruh data ?", "Pesan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
//                namaLengkap.setText(null);
//                username.setText(null);
//                jPasswordField.setText(null);
//                Alamat.setText(null);
//                noHp.setText(null);
//                pop_upClear clear = new pop_upClear();
//                clear.setVisible(true);
//            }
            pop_upTanyaClear pop = new pop_upTanyaClear(this);
            pop.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_hapus1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void noHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHpActionPerformed

    private void jownerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jownerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jownerActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        rfid.setText("");
        rfid.requestFocusInWindow();
    }//GEN-LAST:event_jLabel2MouseClicked
    int i = 0;
    private void rfidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rfidKeyReleased
        RFID = rfid.getText();
        System.out.println(RFID);
    }//GEN-LAST:event_rfidKeyReleased

    private void kodeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeUserActionPerformed

    private void rfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUserv2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUserv2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUserv2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUserv2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUserv2(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JLabel jButton_hapus1;
    private javax.swing.JCheckBox jCheckBox_showpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jadmin;
    private javax.swing.JRadioButton jowner;
    private javax.swing.JTextField kodeUser;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JTextField noHp;
    private javax.swing.JTextField rfid;
    private javax.swing.JLabel save;
    private javax.swing.JButton saveMobil;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
